// =============================================================================
// VERIFICATION HEADER (added 2026-05-28)
// =============================================================================
//
// STATUS: Partial-success artifact. Big wins at seq=4k (2-3x) for all Q.
// Wins at seq=512 mostly (1.08-1.26x). Loses at seq=128 (overhead floor) and
// seq=32k (bandwidth-bound — design doesn't pipeline TMA).
//
// MEASURED (B200 GPU 5, fresh baseline, 2-sec hot warmup, 300 iter median):
//
//   Q\seq   seq128         seq512         seq4k           seq32k
//   Q=2     0.90x          1.08x          2.06x WIN       0.60x LOSS
//   Q=3     0.74x          1.12x          2.97x WIN       0.78x LOSS
//   Q=4     0.82x          1.26x WIN      2.58x WIN       0.56x LOSS
//
// (Kernel TF / FlashInfer FA2 baseline TF; FlashInfer via
// BatchPrefillWithPagedKVCacheWrapper(causal=True), use_tensor_cores=True
// implicit in BatchPrefill on SM100.)
//
// WHY THE PATTERN
//   - seq=4k: FlashInfer's MMA tile padding wastes work at q_len <= 4
//     (q=3 padded up to q=4, etc.). Agent's CUDA-core kernel computes only
//     what's needed → 2-3x win.
//   - seq=512: marginal — both kernels in transition between launch-overhead
//     and compute-bound regimes.
//   - seq=128: both at ~12us launch+init overhead floor. Agent slightly
//     slower because its CTAs incur small extra overhead at this size.
//   - seq=32k: bandwidth-bound. FlashInfer's TC pipeline overlaps memory and
//     compute via warp-specialized TMA gather. Agent's plain ldg+SMEM stage
//     loses ~0.6x in this regime.
//
// CAVEAT
//   The kernel was tuned for seq=4k. The other shapes inherit whatever the
//   seq=4k-tuned design produces — there is no shape-specific optimization
//   in this kernel. To win at seq=128 or seq=32k, different architectures
//   would be needed (smaller launch overhead for seq=128, TMA pipelining
//   for seq=32k).
//
// PROVENANCE
//   Generated by ferret CUDA-kernel agent. Final tag v007.
//   v001: CUDA-core multi-token with causal mask
//   v002: per-token online softmax, no local memory spills
//   v003: chunk_size=32 + vectorized SMEM loads
//   v004: load K,V once per token, share across Q rows
//   v005: Q-dependent chunk_size (64 for Q<=3, 32 for Q=4)
//   v006: simplified SMEM load (no page-crossing check)
//   v007: extend main() to all 12 configs (no kernel changes)
//
// =============================================================================
// Paged GQA Multi-Token Decode (Q_len={2,3,4}) for Qwen3-30B-A3B on B200
// Extends v012 Q=1 CUDA-core architecture to handle multiple query rows with
// causal masking.
//
// Architecture: Split-KV + SMEM-staged KV + warp-per-head
// Each CTA: 256 threads = 8 warps, one warp per QO head
// Each warp processes ALL Q_LEN query rows (causal masked)
// KV loaded once to SMEM, shared across all 8 heads and all Q rows
// =============================================================================

#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_bf16.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <random>
#include <chrono>

using bf16_t = __nv_bfloat16;

static constexpr int HD = 128;
static constexpr int NQH = 8;
static constexpr int NKH = 1;
static constexpr int PS = 4096;
static constexpr int64_t KVS_TOK = (int64_t)NKH * HD;
static constexpr int64_t KVS_KV  = (int64_t)PS * KVS_TOK;
static constexpr int64_t KVS_PAGE = 2 * KVS_KV;

static constexpr int BLK = 256;
static constexpr int CHUNK = 32;

struct SmemLayout {
    bf16_t kbuf[CHUNK][HD];
    bf16_t vbuf[CHUNK][HD];
};

// 8-warp SMEM-staged kernel
template<int QL>
__global__ void __launch_bounds__(BLK)
paged_gqa_multitoken(
    const bf16_t* __restrict__ Q,       // [QL, NQH, HD]
    const bf16_t* __restrict__ paged_kv,
    const int* __restrict__ kv_indices,
    float* __restrict__ pO,             // [nsplits, QL, NQH, HD]
    float* __restrict__ pLSE,           // [nsplits, QL, NQH]
    int seq_len, int chunk_size, float sm_scale_log2,
    int q_len
) {
    __shared__ SmemLayout sm;
    
    const int sid = blockIdx.x;
    const int tid = threadIdx.x;
    const int wid = tid / 32;
    const int lid = tid % 32;
    
    const int ts = sid * chunk_size;
    const int te = min(ts + chunk_size, seq_len);
    
    int causal_end[QL];
    #pragma unroll
    for (int q = 0; q < QL; q++)
        causal_end[q] = seq_len - q_len + 1 + q;
    
    if (ts >= seq_len) {
        #pragma unroll
        for (int q = 0; q < QL; q++) {
            if (lid == 0) pLSE[(sid * QL + q) * NQH + wid] = -INFINITY;
            for (int d = lid; d < HD; d += 32)
                pO[((sid * QL + q) * NQH + wid) * HD + d] = 0.0f;
        }
        return;
    }
    
    float qr[QL][4];
    #pragma unroll
    for (int q = 0; q < QL; q++) {
        #pragma unroll
        for (int i = 0; i < 4; i++)
            qr[q][i] = __bfloat162float(Q[(q * NQH + wid) * HD + lid * 4 + i]);
    }
    
    float m_val[QL], l_val[QL];
    float oa[QL][4];
    #pragma unroll
    for (int q = 0; q < QL; q++) {
        m_val[q] = -INFINITY;
        l_val[q] = 0.0f;
        #pragma unroll
        for (int i = 0; i < 4; i++)
            oa[q][i] = 0.0f;
    }
    
    for (int cs = ts; cs < te; cs += CHUNK) {
        int ce = min(cs + CHUNK, te);
        int cl = ce - cs;
        
        // Load K and V to SMEM (all threads cooperate)
        {
            const int pl0 = cs / PS;
            const int tip0 = cs % PS;
            const int pp0 = __ldg(kv_indices + pl0);
            const bf16_t* kbase0 = paged_kv + (int64_t)pp0 * KVS_PAGE + (int64_t)tip0 * KVS_TOK;
            const bf16_t* vbase0 = kbase0 + KVS_KV;
            
            // With PAGE_SIZE=4096 and CHUNK<=64, never crosses page boundary
            const int total_u4 = cl * (HD / 8);
            for (int idx = tid; idx < total_u4; idx += BLK) {
                int tok_local = idx / (HD / 8);
                int u4_idx = idx % (HD / 8);
                const bf16_t* kp = kbase0 + (int64_t)tok_local * KVS_TOK;
                const bf16_t* vp = vbase0 + (int64_t)tok_local * KVS_TOK;
                ((uint4*)sm.kbuf[tok_local])[u4_idx] = __ldg(((const uint4*)kp) + u4_idx);
                ((uint4*)sm.vbuf[tok_local])[u4_idx] = __ldg(((const uint4*)vp) + u4_idx);
            }
        }
        __syncthreads();
        
        // QK^T + online softmax + PV: load K,V once, process all Q rows
        {
            int min_ecl = max(min(ce, causal_end[0]) - cs, 0);
            int max_ecl = max(min(ce, causal_end[QL-1]) - cs, 0);
            
            #pragma unroll 4
            for (int t = 0; t < min_ecl; t++) {
                uint32_t kw0 = ((const uint32_t*)sm.kbuf[t])[lid * 2];
                uint32_t kw1 = ((const uint32_t*)sm.kbuf[t])[lid * 2 + 1];
                float k0 = __bfloat162float(*reinterpret_cast<const bf16_t*>(&kw0));
                float k1 = __bfloat162float(*(reinterpret_cast<const bf16_t*>(&kw0) + 1));
                float k2 = __bfloat162float(*reinterpret_cast<const bf16_t*>(&kw1));
                float k3 = __bfloat162float(*(reinterpret_cast<const bf16_t*>(&kw1) + 1));
                
                uint32_t vw0 = ((const uint32_t*)sm.vbuf[t])[lid * 2];
                uint32_t vw1 = ((const uint32_t*)sm.vbuf[t])[lid * 2 + 1];
                float v0 = __bfloat162float(*reinterpret_cast<const bf16_t*>(&vw0));
                float v1 = __bfloat162float(*(reinterpret_cast<const bf16_t*>(&vw0) + 1));
                float v2 = __bfloat162float(*reinterpret_cast<const bf16_t*>(&vw1));
                float v3 = __bfloat162float(*(reinterpret_cast<const bf16_t*>(&vw1) + 1));
                
                #pragma unroll
                for (int q = 0; q < QL; q++) {
                    float dot = qr[q][0]*k0 + qr[q][1]*k1 + qr[q][2]*k2 + qr[q][3]*k3;
                    #pragma unroll
                    for (int o = 16; o > 0; o >>= 1)
                        dot += __shfl_xor_sync(0xFFFFFFFF, dot, o);
                    float score = dot * sm_scale_log2;
                    
                    float nm = fmaxf(m_val[q], score);
                    float corr = exp2f(m_val[q] - nm);
                    float p = exp2f(score - nm);
                    
                    oa[q][0] = oa[q][0] * corr + p * v0;
                    oa[q][1] = oa[q][1] * corr + p * v1;
                    oa[q][2] = oa[q][2] * corr + p * v2;
                    oa[q][3] = oa[q][3] * corr + p * v3;
                    l_val[q] = l_val[q] * corr + p;
                    m_val[q] = nm;
                }
            }
            
            for (int t = min_ecl; t < max_ecl; t++) {
                uint32_t kw0 = ((const uint32_t*)sm.kbuf[t])[lid * 2];
                uint32_t kw1 = ((const uint32_t*)sm.kbuf[t])[lid * 2 + 1];
                float k0 = __bfloat162float(*reinterpret_cast<const bf16_t*>(&kw0));
                float k1 = __bfloat162float(*(reinterpret_cast<const bf16_t*>(&kw0) + 1));
                float k2 = __bfloat162float(*reinterpret_cast<const bf16_t*>(&kw1));
                float k3 = __bfloat162float(*(reinterpret_cast<const bf16_t*>(&kw1) + 1));
                
                uint32_t vw0 = ((const uint32_t*)sm.vbuf[t])[lid * 2];
                uint32_t vw1 = ((const uint32_t*)sm.vbuf[t])[lid * 2 + 1];
                float v0 = __bfloat162float(*reinterpret_cast<const bf16_t*>(&vw0));
                float v1 = __bfloat162float(*(reinterpret_cast<const bf16_t*>(&vw0) + 1));
                float v2 = __bfloat162float(*reinterpret_cast<const bf16_t*>(&vw1));
                float v3 = __bfloat162float(*(reinterpret_cast<const bf16_t*>(&vw1) + 1));
                
                #pragma unroll
                for (int q = 0; q < QL; q++) {
                    if (cs + t >= causal_end[q]) continue;
                    float dot = qr[q][0]*k0 + qr[q][1]*k1 + qr[q][2]*k2 + qr[q][3]*k3;
                    #pragma unroll
                    for (int o = 16; o > 0; o >>= 1)
                        dot += __shfl_xor_sync(0xFFFFFFFF, dot, o);
                    float score = dot * sm_scale_log2;
                    float nm = fmaxf(m_val[q], score);
                    float corr = exp2f(m_val[q] - nm);
                    float p = exp2f(score - nm);
                    oa[q][0] = oa[q][0] * corr + p * v0;
                    oa[q][1] = oa[q][1] * corr + p * v1;
                    oa[q][2] = oa[q][2] * corr + p * v2;
                    oa[q][3] = oa[q][3] * corr + p * v3;
                    l_val[q] = l_val[q] * corr + p;
                    m_val[q] = nm;
                }
            }
        }
        __syncthreads();
    }
    
    #pragma unroll
    for (int q = 0; q < QL; q++) {
        float inv_l = (l_val[q] > 0.0f) ? __fdividef(1.0f, l_val[q]) : 0.0f;
        float lse = (l_val[q] > 0.0f) ? (m_val[q] + __log2f(l_val[q])) : -INFINITY;
        if (lid == 0) pLSE[(sid * QL + q) * NQH + wid] = lse;
        #pragma unroll
        for (int i = 0; i < 4; i++)
            pO[((sid * QL + q) * NQH + wid) * HD + lid * 4 + i] = oa[q][i] * inv_l;
    }
}

// ========================= Combine Kernel =========================
template<int QL>
__global__ void combine_kernel_mt(
    const float* __restrict__ pO, const float* __restrict__ pLSE,
    bf16_t* __restrict__ Out, int nsplits
) {
    // blockIdx.x = q * NQH + h, threadIdx.x = d
    int qh = blockIdx.x;
    int q = qh / NQH;
    int h = qh % NQH;
    int d = threadIdx.x;
    if (q >= QL || h >= NQH || d >= HD) return;
    
    float mx = -INFINITY;
    for (int s = 0; s < nsplits; s++)
        mx = fmaxf(mx, pLSE[(s * QL + q) * NQH + h]);
    
    float so = 0, sw = 0;
    for (int s = 0; s < nsplits; s++) {
        float w = exp2f(pLSE[(s * QL + q) * NQH + h] - mx);
        sw += w;
        so += w * pO[((s * QL + q) * NQH + h) * HD + d];
    }
    Out[(q * NQH + h) * HD + d] = __float2bfloat16(sw > 0 ? __fdividef(so, sw) : 0.0f);
}

// ========================= Host =========================
void chk(cudaError_t e, const char* m) {
    if (e != cudaSuccess) { fprintf(stderr, "CUDA(%s):%s\n", m, cudaGetErrorString(e)); exit(1); }
}

void cpu_ref_multitoken(const bf16_t* Q, const bf16_t* kv, const int* ki,
                         int q_len, int sl, float sms, float* out) {
    for (int q = 0; q < q_len; q++) {
        int causal_end = sl - q_len + 1 + q;
        for (int h = 0; h < NQH; h++) {
            float qv[HD];
            for (int d = 0; d < HD; d++)
                qv[d] = __bfloat162float(Q[(q * NQH + h) * HD + d]);
            
            float m = -INFINITY, l = 0;
            float o[HD] = {};
            for (int t = 0; t < causal_end; t++) {
                int pl = t / PS, tip = t % PS, pp = ki[pl];
                const bf16_t* k = kv + (int64_t)pp * KVS_PAGE + (int64_t)tip * KVS_TOK;
                float dot = 0;
                for (int d = 0; d < HD; d++)
                    dot += qv[d] * __bfloat162float(k[d]);
                float sc = dot * sms;
                float nm = fmaxf(m, sc);
                float c = expf(m - nm);
                float p = expf(sc - nm);
                l = l * c + p;
                const bf16_t* v = kv + (int64_t)pp * KVS_PAGE + KVS_KV + (int64_t)tip * KVS_TOK;
                for (int d = 0; d < HD; d++)
                    o[d] = o[d] * c + p * __bfloat162float(v[d]);
                m = nm;
            }
            float il = l > 0 ? 1.0f / l : 0;
            for (int d = 0; d < HD; d++)
                out[(q * NQH + h) * HD + d] = o[d] * il;
        }
    }
}

template<int QL>
double run_config(const char* name, int q_len, int seq_len, float sms, void* df, size_t fs) {
    int np = (seq_len + PS - 1) / PS;
    size_t qs = (size_t)q_len * NQH * HD;
    
    std::mt19937 rng(42);
    std::uniform_real_distribution<float> dist(-0.5f, 0.5f);
    
    // Use position-dependent values for K,V so causal mask bugs show up
    std::vector<bf16_t> hq(qs);
    for (size_t i = 0; i < qs; i++) hq[i] = __float2bfloat16(dist(rng));
    
    size_t kvt = (size_t)np * 2 * PS * NKH * HD;
    std::vector<bf16_t> hkv(kvt);
    for (size_t i = 0; i < kvt; i++) hkv[i] = __float2bfloat16(dist(rng));
    
    std::vector<int> hki(np);
    for (int i = 0; i < np; i++) hki[i] = i;
    
    bf16_t *dq, *dkv, *dout;
    int *dki;
    chk(cudaMalloc(&dq, qs * 2), "");
    chk(cudaMalloc(&dkv, kvt * 2), "");
    chk(cudaMalloc(&dout, qs * 2), "");
    chk(cudaMalloc(&dki, np * 4), "");
    chk(cudaMemcpy(dq, hq.data(), qs * 2, cudaMemcpyHostToDevice), "");
    chk(cudaMemcpy(dkv, hkv.data(), kvt * 2, cudaMemcpyHostToDevice), "");
    chk(cudaMemcpy(dki, hki.data(), np * 4, cudaMemcpyHostToDevice), "");
    
    // Adaptive chunk_size: small for short seq (parallelism), large for long seq (reduce combine)
    int kvc;
    if (seq_len <= 4096) {
        kvc = (QL <= 3) ? 64 : 32;
    } else {
        // For long seq, target ~64 splits to keep combine overhead low
        kvc = (seq_len + 63) / 64;
        // Round up to multiple of CHUNK(32) 
        kvc = ((kvc + 31) / 32) * 32;
    }
    int ns = (seq_len + kvc - 1) / kvc;
    
    float *dpO, *dpL;
    chk(cudaMalloc(&dpO, (size_t)ns * QL * NQH * HD * 4), "");
    chk(cudaMalloc(&dpL, (size_t)ns * QL * NQH * 4), "");
    
    float sml2 = sms * 1.4426950408889634f;
    
    auto run = [&]() {
        paged_gqa_multitoken<QL><<<ns, BLK>>>(dq, dkv, dki, dpO, dpL, seq_len, kvc, sml2, q_len);
        combine_kernel_mt<QL><<<QL * NQH, HD>>>(dpO, dpL, dout, ns);
    };
    
    run();
    chk(cudaDeviceSynchronize(), "sync");
    
    // Validate
    std::vector<float> ref(qs);
    cpu_ref_multitoken(hq.data(), hkv.data(), hki.data(), q_len, seq_len, sms, ref.data());
    std::vector<bf16_t> gout(qs);
    chk(cudaMemcpy(gout.data(), dout, qs * 2, cudaMemcpyDeviceToHost), "");
    
    float mre = 0, mae = 0, sae = 0;
    for (size_t i = 0; i < qs; i++) {
        float g = __bfloat162float(gout[i]), r = ref[i];
        float ae = fabsf(g - r), re = ae / fmaxf(fabsf(r), 1e-6f);
        mre = fmaxf(mre, re);
        mae = fmaxf(mae, ae);
        sae += ae;
    }
    float meae = sae / qs;
    bool valid = (mre < 1e-2f) && (mae < 1.0f) && (meae < 1e-2f);
    fprintf(stderr, "%s (Q=%d): mre=%.6f mae=%.6f meae=%.6f %s\n",
            name, q_len, mre, mae, meae, valid ? "PASS" : "INVALID");
    
    double tflops = 0;
    if (valid) {
        // Warmup >= 2 seconds
        auto t0 = std::chrono::steady_clock::now();
        while (true) {
            run();
            cudaDeviceSynchronize();
            auto t1 = std::chrono::steady_clock::now();
            double elapsed = std::chrono::duration<double>(t1 - t0).count();
            if (elapsed >= 2.0) break;
        }
        
        int NI = 300;
        std::vector<float> ts(NI);
        for (int it = 0; it < NI; it++) {
            cudaMemset(df, 0, fs);
            cudaEvent_t s, e;
            cudaEventCreate(&s);
            cudaEventCreate(&e);
            cudaEventRecord(s);
            run();
            cudaEventRecord(e);
            cudaEventSynchronize(e);
            float ms;
            cudaEventElapsedTime(&ms, s, e);
            ts[it] = ms;
            cudaEventDestroy(s);
            cudaEventDestroy(e);
        }
        std::sort(ts.begin(), ts.end());
        float med = ts[NI / 2];
        
        // FLOPS = 4 * NQH * HD * Q * (SEQ_LEN - (Q-1)/2.0)
        double total_attended = (double)q_len * seq_len - (double)q_len * (q_len - 1) / 2.0;
        double flops = 4.0 * NQH * total_attended * HD;
        tflops = flops / (med / 1000.0) / 1e12;
        fprintf(stderr, "%s: %.4f TFLOPS, %.1f us\n", name, tflops, med * 1000);
    }
    
    cudaFree(dq); cudaFree(dkv); cudaFree(dout); cudaFree(dki);
    cudaFree(dpO); cudaFree(dpL);
    return valid ? tflops : 0.0;
}

struct Config {
    const char* name;
    int q_len;
    int seq_len;
};

int main() {
    chk(cudaSetDevice(0), "sd");
    float sms = 1.0f / sqrtf((float)HD);
    size_t fs = 128 * 1024 * 1024;
    void* df;
    chk(cudaMalloc(&df, fs), "f");
    
    Config configs[] = {
        {"q2_seq128",  2,   128},
        {"q2_seq512",  2,   512},
        {"q2_seq4k",   2,  4096},
        {"q2_seq32k",  2, 32768},
        {"q3_seq128",  3,   128},
        {"q3_seq512",  3,   512},
        {"q3_seq4k",   3,  4096},
        {"q3_seq32k",  3, 32768},
        {"q4_seq128",  4,   128},
        {"q4_seq512",  4,   512},
        {"q4_seq4k",   4,  4096},
        {"q4_seq32k",  4, 32768},
    };
    int ncfg = sizeof(configs) / sizeof(configs[0]);
    
    double results[12] = {};
    
    for (int ci = 0; ci < ncfg; ci++) {
        Config& c = configs[ci];
        double r = 0;
        if (c.q_len == 2)
            r = run_config<2>(c.name, c.q_len, c.seq_len, sms, df, fs);
        else if (c.q_len == 3)
            r = run_config<3>(c.name, c.q_len, c.seq_len, sms, df, fs);
        else
            r = run_config<4>(c.name, c.q_len, c.seq_len, sms, df, fs);
        results[ci] = r;
    }
    
    // Print KERNEL_RESULT
    printf("KERNEL_RESULT {");
    for (int i = 0; i < ncfg; i++) {
        if (i) printf(", ");
        printf("\"%s\": %.4f", configs[i].name, results[i]);
    }
    printf("}\n");
    fflush(stdout);
    
    // Run baseline
    fflush(stderr);
    FILE* bp = popen("python3 ../baselines/paged-gqa-multitoken-qwen3/baseline.py 2>/dev/null", "r");
    double rv[12] = {};
    if (bp) {
        char l[1024];
        while (fgets(l, sizeof(l), bp)) {
            for (int i = 0; i < ncfg; i++) {
                char prefix[64];
                snprintf(prefix, sizeof(prefix), "%s:", configs[i].name);
                char* p = strstr(l, prefix);
                if (p) {
                    p += strlen(prefix);
                    while (*p == ' ') p++;
                    rv[i] = atof(p);
                }
            }
        }
        pclose(bp);
    }
    printf("KERNEL_RESULT_REFERENCE {");
    for (int i = 0; i < ncfg; i++) {
        if (i) printf(", ");
        printf("\"%s\": %.4f", configs[i].name, rv[i]);
    }
    printf("}\n");
    fflush(stdout);
    
    cudaFree(df);
    return 0;
}
