// =============================================================================
// FP8 MLA Sparse Decode for DeepSeek V4 (MODEL1 layout)
// Target: NVIDIA Blackwell B200 (sm_100a)
//
// STATUS: Partial match. Closes the gap to FlashMLA on 4/6 configs; the
// heaviest production shapes (b64_v4pro, b128_v4pro) still 0.79-0.88x of
// FlashMLA. Saved as the agent's best legitimate FlashMLA-free kernel
// before narrowing the task to b64_v4pro + b128_v4pro for further work.
//
// MEASURED PERFORMANCE (B200, hot GPU, L2 flush, same methodology as FlashMLA
// baseline, V4 MODEL1 layout 584 bytes/tok)
//
//                       this kernel       FlashMLA        ratio
//   b2_v4flash    h_q=64    15.60 TFLOPS    13.64 TFLOPS    1.144x
//   b64_v4flash   h_q=64   283.16          282.92          1.001x
//   b128_v4flash  h_q=64   322.95          332.88          0.970x
//   b2_v4pro      h_q=128   51.29           49.09          1.045x
//   b64_v4pro     h_q=128  397.49          449.22          0.885x  <-- gap
//   b128_v4pro    h_q=128  452.08          576.18          0.785x  <-- gap
//
//   All shapes: s_q=2 (MTP), h_kv=1, s_kv=16384, topk=128, extra_s_k=16384,
//               d_qk=512, d_v=512, block_size=256, extra_block_size=64.
//   V4-Flash configs: extra_topk=512.  V4-Pro configs: extra_topk=1024.
//
// ARCHITECTURE
//   - 3-warpgroup warp specialization:
//       WG0 = softmax + epilogue (LSE accumulation, output store)
//       WG1 = MMA + TMA-load + index handling (QK^T and PV via tcgen05)
//       WG2 = FP8 dequant (e8m0 scale unpack + bf16 multiply, in registers)
//   - BF16 tcgen05 MMA (kind::f16 with bf16 operands) -- same as FlashMLA's
//     SM100_MMA_F16BF16_WS_*. FP8 KV is dequantized to BF16 in registers
//     before MMA. NOT hardware FP8 MMA (kind::f8f6f4 / mxf8f6f4.block_scale).
//   - mbarrier-only batch transitions (no 384-thread named_bar_sync); each
//     WG synchronizes via its own mbarrier protocol.
//   - --use_fast_math compiler flag (~+8% on b128_v4pro).
//   - Self-contained: NO #include from resources/flashmla-main/. All MMA
//     atoms, TMA helpers, and sync primitives are CUTLASS-only or inline-PTX
//     written here. Only links -lcuda -lcudart.
//
// WHERE THE GAP IS (NCU analysis from agent's progress.md)
//   - Barrier stalls (~9.15 stall ratio) dominate b128_v4pro
//   - Memory pipeline at large extra_topk=1024 is not fully overlapping MMA
//   - "BF16 MMA optimizations exhausted" per agent's iter-24 notes
//
// WHY THIS WON'T REACH 1.20x AS-IS
//   FlashMLA uses the same BF16-MMA-on-dequantized-FP8 architecture (see
//   csrc/sm100/decode/head64/config.h: SM100_MMA_F16BF16_WS_*). To go
//   beyond FlashMLA's perf, you'd need a real architectural deviation --
//   most likely hardware FP8 MMA (tcgen05.mma.kind::mxf8f6f4.block_scale)
//   which would skip the dequant step entirely.
//
// PROVENANCE
//   Generated by ferret CUDA-kernel agent across multiple resume cycles,
//   2026-05-11 to 2026-05-12. Final tag v033 (commit 6efd87a in workspace).
//   Notable architectural milestones in the agent's commit chain:
//     v029: removed FlashMLA includes, switched to self-contained MMA atoms
//     v030: unroll prevention on Scale O + epilogue, WG0 regs=200
//     v031: PDL completion + fixed_overhead=1 for v4pro scheduler
//     v032: --use_fast_math (+8% on b128_v4pro)
//     v033: mbarrier-only batch transitions (+5% on most configs)
// =============================================================================

// FP8 MLA Decode for DeepSeek V4 (MODEL1) -- 3-warpgroup warp-specialized kernel
// Architecture: WG0=softmax/epilogue, WG1=MMA/TMA/index, WG2=dequant
// Following FlashMLA sm100 decode head64 MODEL1 architecture
// BUILD: nvcc -O3 --use_fast_math -std=c++17 -gencode arch=compute_100a,code=sm_100a
#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_fp8.h>
#include <cuda_bf16.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <algorithm>
#include <vector>
#include <random>
#include <unistd.h>
#include <cute/tensor.hpp>
#include <cute/arch/tmem_allocator_sm100.hpp>
#include <cutlass/barrier.h>
#include <cutlass/arch/barrier.h>
#include <cutlass/arch/reg_reconfig.h>
#include <cute/algorithm/cooperative_copy.hpp>

// ---- Self-contained struct definitions (from FlashMLA params.h) ----
struct __align__(4*8) DecodingSchedMeta {
    int begin_req_idx, end_req_idx;
    int begin_block_idx, end_block_idx;
    int begin_split_idx;
    int is_first_req_splitted, is_last_req_splitted;
    int _pad[1];
};
struct CombineParams {
    int b, s_q, h_q, d_v;
    float* __restrict__ lse;
    void* __restrict__ out;
    int stride_lse_b, stride_lse_s_q;
    int stride_o_b, stride_o_s_q, stride_o_h_q;
    float* __restrict__ lse_accum;
    float* __restrict__ o_accum;
    int stride_lse_accum_split, stride_lse_accum_s_q;
    int stride_o_accum_split, stride_o_accum_s_q, stride_o_accum_h_q;
    DecodingSchedMeta* __restrict__ tile_scheduler_metadata_ptr;
    int* __restrict__ num_splits_ptr;
    int num_sm_parts;
    float* attn_sink;
    cudaStream_t stream;
};
struct GetDecodeSchedMetaParams {
    int b, s_q, block_size_n, fixed_overhead_num_blocks;
    int topk, extra_topk;
    int *__restrict__ topk_length, *__restrict__ extra_topk_length;
    int *__restrict__ seqlens_k_ptr;
    DecodingSchedMeta *__restrict__ tile_scheduler_metadata_ptr;
    int *__restrict__ num_splits_ptr;
    int num_sm_parts;
    cudaStream_t stream;
};

// ---- Self-contained MMA atoms (equivalent to FlashMLA's WS NOELECT variants) ----
namespace cute {

// TS (TMEM-SMEM) warp-specialized MMA without elect_one_sync
template <class a_type, class b_type, class c_type,
          int M, int N, UMMA::Major a_major, UMMA::Major b_major,
          UMMA::ScaleIn a_neg = UMMA::ScaleIn::One, UMMA::ScaleIn b_neg = UMMA::ScaleIn::One>
struct SM100_MMA_F16BF16_WS_TS_NOELECT {
    using DRegisters = void;
    using ARegisters = uint64_t[1];
    using BRegisters = uint64_t[1];
    using CRegisters = uint32_t[1];
    CUTE_HOST_DEVICE static void fma(uint32_t const& tmem_a, uint64_t const& desc_b,
        uint32_t const& tmem_c, uint32_t const& scaleC, uint64_t const& idescE) {
        asm volatile(
            "{\n\t.reg .pred p;\n\tsetp.ne.b32 p, %4, 0;\n\t"
            "tcgen05.mma.ws.cta_group::1.kind::f16 [%0], [%1], %2, %3, p, 0;\n}\n"
            :: "r"(tmem_c), "r"(tmem_a), "l"(desc_b), "r"(uint32_t(idescE>>32)), "r"(scaleC));
    }
};

template <class a_type, class b_type, class c_type,
          int M, int N, UMMA::Major a_major, UMMA::Major b_major,
          UMMA::ScaleIn a_neg, UMMA::ScaleIn b_neg>
struct MMA_Traits<SM100_MMA_F16BF16_WS_TS_NOELECT<a_type,b_type,c_type,M,N,a_major,b_major,a_neg,b_neg>> {
    using ValTypeD = c_type; using ValTypeA = a_type; using ValTypeB = b_type; using ValTypeC = c_type;
    using FrgTypeA = UMMA::tmem_frg_1sm<a_type, a_type, UMMA::TmemAllocMode::NonInterleaved>;
    using FrgTypeB = UMMA::smem_desc<b_major>;
    using FrgTypeC = UMMA::tmem_frg_ws_1sm<c_type>;
    static constexpr int K = 256 / sizeof_bits<ValTypeA>::value;
    using Shape_MNK = Shape<Int<M>,Int<N>,Int<K>>;
    using ThrID = Layout<_1>;
    using ALayout = Layout<Shape<_1,Shape<Int<M>,Int<K>>>,Stride<_0,Stride<_1,Int<M>>>>;
    using BLayout = Layout<Shape<_1,Shape<Int<N>,Int<K>>>,Stride<_0,Stride<_1,Int<N>>>>;
    using CLayout = Layout<Shape<_1,Shape<Int<M>,Int<N>>>,Stride<_0,Stride<_1,Int<M>>>>;
    UMMA::ScaleOut accumulate_ = UMMA::ScaleOut::One;
    UMMA::InstrDescriptor idesc_ = UMMA::make_instr_desc<a_type,b_type,c_type,M,N,a_major,b_major,a_neg,b_neg>();
    template <class TD, class DLayout_, class TA, class ALayout_, class TB, class BLayout_, class TC, class CLayout_>
    CUTE_HOST_DEVICE constexpr friend void mma_unpack(
        MMA_Traits const& traits, Tensor<TD,DLayout_>& D, Tensor<TA,ALayout_> const& A,
        Tensor<TB,BLayout_> const& B, Tensor<TC,CLayout_> const& C) {
        uint32_t tmem_a = raw_pointer_cast(A.data());
        uint64_t desc_b = B[0];
        uint32_t tmem_c = raw_pointer_cast(D.data());
        uint64_t idesc = UMMA::make_runtime_instr_desc<>(traits.idesc_);
        SM100_MMA_F16BF16_WS_TS_NOELECT<a_type,b_type,c_type,M,N,a_major,b_major,a_neg,b_neg>::fma(
            tmem_a, desc_b, tmem_c, uint32_t(traits.accumulate_), idesc);
    }
};

// SS (SMEM-SMEM) warp-specialized MMA without elect_one_sync
template <class a_type, class b_type, class c_type,
          int M, int N, UMMA::Major a_major, UMMA::Major b_major,
          UMMA::ScaleIn a_neg = UMMA::ScaleIn::One, UMMA::ScaleIn b_neg = UMMA::ScaleIn::One>
struct SM100_MMA_F16BF16_WS_SS_NOELECT {
    using DRegisters = void;
    using ARegisters = uint64_t[1];
    using BRegisters = uint64_t[1];
    using CRegisters = uint32_t[1];
    CUTE_HOST_DEVICE static void fma(uint64_t const& desc_a, uint64_t const& desc_b,
        uint32_t const& tmem_c, uint32_t const& scaleC, uint64_t const& idescE) {
        asm volatile(
            "{\n\t.reg .pred p;\n\tsetp.ne.b32 p, %4, 0;\n\t"
            "tcgen05.mma.ws.cta_group::1.kind::f16 [%0], %1, %2, %3, p, 0;\n}\n"
            :: "r"(tmem_c), "l"(desc_a), "l"(desc_b), "r"(uint32_t(idescE>>32)), "r"(scaleC));
    }
};

template <class a_type, class b_type, class c_type,
          int M, int N, UMMA::Major a_major, UMMA::Major b_major,
          UMMA::ScaleIn a_neg, UMMA::ScaleIn b_neg>
struct MMA_Traits<SM100_MMA_F16BF16_WS_SS_NOELECT<a_type,b_type,c_type,M,N,a_major,b_major,a_neg,b_neg>> {
    using ValTypeD = c_type; using ValTypeA = a_type; using ValTypeB = b_type; using ValTypeC = c_type;
    using FrgTypeA = UMMA::smem_desc<a_major>;
    using FrgTypeB = UMMA::smem_desc<b_major>;
    using FrgTypeC = UMMA::tmem_frg_ws_1sm<c_type>;
    static constexpr int K = 256 / sizeof_bits<ValTypeA>::value;
    using Shape_MNK = Shape<Int<M>,Int<N>,Int<K>>;
    using ThrID = Layout<_1>;
    using ALayout = Layout<Shape<_1,Shape<Int<M>,Int<K>>>,Stride<_0,Stride<_1,Int<M>>>>;
    using BLayout = Layout<Shape<_1,Shape<Int<N>,Int<K>>>,Stride<_0,Stride<_1,Int<N>>>>;
    using CLayout = Layout<Shape<_1,Shape<Int<M>,Int<N>>>,Stride<_0,Stride<_1,Int<M>>>>;
    UMMA::InstrDescriptor idesc_ = UMMA::make_instr_desc<a_type,b_type,c_type,M,N,a_major,b_major,a_neg,b_neg>();
    UMMA::ScaleOut accumulate_ = UMMA::ScaleOut::One;
    template <class TD, class DLayout_, class TA, class ALayout_, class TB, class BLayout_, class TC, class CLayout_>
    CUTE_HOST_DEVICE constexpr friend void mma_unpack(
        MMA_Traits const& traits, Tensor<TD,DLayout_>& D, Tensor<TA,ALayout_> const& A,
        Tensor<TB,BLayout_> const& B, Tensor<TC,CLayout_> const& C) {
        uint64_t desc_a = A[0];
        uint64_t desc_b = B[0];
        uint32_t tmem_c = raw_pointer_cast(D.data());
        uint64_t idesc = UMMA::make_runtime_instr_desc<>(traits.idesc_);
        SM100_MMA_F16BF16_WS_SS_NOELECT<a_type,b_type,c_type,M,N,a_major,b_major,a_neg,b_neg>::fma(
            desc_a, desc_b, tmem_c, uint32_t(traits.accumulate_), idesc);
    }
};

} // namespace cute

// ---- Self-contained UTCMMA helper functions ----
namespace myutils {
template<typename TiledMMA, typename TensorA, typename TensorB, typename TensorFragC>
CUTE_DEVICE void utcmma_ss(TiledMMA &tiled_mma, TensorA sA, TensorB sB, TensorFragC tC_frag, bool clear_accum) {
    using namespace cute;
    tiled_mma.accumulate_ = clear_accum ? UMMA::ScaleOut::Zero : UMMA::ScaleOut::One;
    auto thr_mma = tiled_mma.get_slice(_0{});
    auto sA_frag = thr_mma.partition_fragment_A(sA);
    auto sB_frag = thr_mma.partition_fragment_B(sB);
    CUTE_UNROLL
    for (int k = 0; k < size<2>(sA_frag); ++k) {
        cute::gemm(tiled_mma, sA_frag(_,_,k), sB_frag(_,_,k), tC_frag);
        tiled_mma.accumulate_ = UMMA::ScaleOut::One;
    }
}
template<typename TiledMMA, typename TensorA, typename TensorB, typename TensorFragC>
CUTE_DEVICE void utcmma_ts(TiledMMA &tiled_mma, TensorA tA_frag, TensorB sB, TensorFragC tC_frag, bool clear_accum) {
    using namespace cute;
    tiled_mma.accumulate_ = clear_accum ? UMMA::ScaleOut::Zero : UMMA::ScaleOut::One;
    auto thr_mma = tiled_mma.get_slice(_0{});
    auto sB_frag = thr_mma.partition_fragment_B(sB);
    CUTE_UNROLL
    for (int k = 0; k < size<2>(tA_frag); ++k) {
        cute::gemm(tiled_mma, tA_frag(_,_,k), sB_frag(_,_,k), tC_frag);
        tiled_mma.accumulate_ = UMMA::ScaleOut::One;
    }
}
} // namespace myutils
using namespace cute;
using bf16_t = cutlass::bfloat16_t;
using e4m3_t = cutlass::float_e4m3_t;
static constexpr int D_QK=512,D_V=512,D_NOPE=448,D_ROPE=64;
static constexpr int QUANT_TILE=64,NUM_SCALES=7;
static constexpr int BYTES_PER_TOKEN=D_NOPE+2*D_ROPE+NUM_SCALES+1;
static constexpr int B_H=64,B_TOPK=64;
static constexpr int TMA_K_STRIDE=D_NOPE+2*D_ROPE; // 576
static constexpr int NUM_BUFS=2,NUM_INDEX_BUFS=4;
static constexpr int NUM_SCALES_EACH=8;
static constexpr int NUM_THREADS=384;
static constexpr float MAX_INIT_VAL=-1e30f;
// Named barrier IDs
enum NB : uint32_t { nb_wg0_sync=1, nb_wg0_w02=2, nb_wg0_w13=3, nb_everyone=4 };
// ---- Device helpers ----
__device__ __forceinline__ bool elect() {
    uint32_t p=0; asm volatile("{.reg .pred %%px; elect.sync _|%%px, 0xFFFFFFFF; @%%px mov.s32 %0,1;}":"+r"(p)); return p;
}
__device__ __forceinline__ void bar_init(void*p,int c){uint32_t a=cute::cast_smem_ptr_to_uint(p);asm volatile("mbarrier.init.shared::cta.b64 [%0],%1;":: "r"(a),"r"(c));}
__device__ __forceinline__ void bar_wait(void*p,int ph){uint32_t a=cute::cast_smem_ptr_to_uint(p);asm volatile("{.reg .pred P1;LW: mbarrier.try_wait.parity.acquire.cta.shared::cta.b64 P1,[%0],%1,0x989680;@P1 bra.uni DN;bra.uni LW;DN:}"::"r"(a),"r"(ph));}
__device__ __forceinline__ void bar_arrive(void*p){uint32_t a=cute::cast_smem_ptr_to_uint(p);asm volatile("mbarrier.arrive.release.cta.shared::cta.b64 _,[%0];":: "r"(a):"memory");}
__device__ __forceinline__ void bar_arrive_tx(void*p,uint32_t b){uint32_t a=cute::cast_smem_ptr_to_uint(p);asm volatile("mbarrier.arrive.expect_tx.release.cta.shared::cta.b64 _,[%0],%1;":: "r"(a),"r"(b):"memory");}
__device__ __forceinline__ void tma_gather4(const void*desc,void*bar,void*smem,int col,int4 rows,int64_t hint){
    uint32_t sa=cute::cast_smem_ptr_to_uint(smem),ba=cute::cast_smem_ptr_to_uint(bar);
    asm volatile("cp.async.bulk.tensor.2d.shared::cta.global.tile::gather4.mbarrier::complete_tx::bytes.cta_group::1.L2::cache_hint [%0],[%1,{%2,%3,%4,%5,%6}],[%7],%8;"
        ::"r"(sa),"l"(desc),"r"(col),"r"(rows.x),"r"(rows.y),"r"(rows.z),"r"(rows.w),"r"(ba),"l"(hint):"memory");
}
__device__ __forceinline__ void umma_arrive_bar(void*bar){uint32_t a=cute::cast_smem_ptr_to_uint(bar);asm volatile("tcgen05.commit.cta_group::1.mbarrier::arrive::one.shared::cluster.b64 [%0];":: "r"(a):"memory");}
__device__ __forceinline__ void named_bar_sync(int id,int cnt){asm volatile("bar.sync %0,%1;":: "r"(id),"r"(cnt));}
__device__ __forceinline__ void named_bar_arrive_wait(int id,int cnt){asm volatile("bar.sync %0,%1;":: "r"(id),"r"(cnt));}
__device__ __forceinline__ void named_bar_arrive(int id,int cnt){asm volatile("bar.arrive %0,%1;":: "r"(id),"r"(cnt));}
// float2 ops
__device__ __forceinline__ float2 f2add(float2 a,float2 b){float2 c;asm volatile("add.f32x2 %0,%1,%2;":"=l"(*(uint64_t*)&c):"l"(*(uint64_t*)&a),"l"(*(uint64_t*)&b));return c;}
__device__ __forceinline__ float2 f2mul(float2 a,float2 b){float2 c;asm volatile("mul.f32x2 %0,%1,%2;":"=l"(*(uint64_t*)&c):"l"(*(uint64_t*)&a),"l"(*(uint64_t*)&b));return c;}
__device__ __forceinline__ float2 f2fma(float2 a,float2 b,float2 c){float2 d;asm volatile("fma.rn.f32x2 %0,%1,%2,%3;":"=l"(*(uint64_t*)&d):"l"(*(uint64_t*)&a),"l"(*(uint64_t*)&b),"l"(*(uint64_t*)&c));return d;}
__device__ __forceinline__ __nv_bfloat162 fp8x2_bf16x2_scale(__nv_fp8x2_e4m3 d,__nv_bfloat16 s){float2 f=(float2)d;__nv_bfloat162 b=__float22bfloat162_rn(f);return __nv_bfloat162{__hmul(b.x,s),__hmul(b.y,s)};}
// TMEM ld/st helpers
template<int N> __device__ __forceinline__ void tmem_ld_32dp(uint32_t col,float*out);
template<> __device__ __forceinline__ void tmem_ld_32dp<32>(uint32_t col,float*out){
    uint32_t*d=(uint32_t*)out;
    asm volatile("tcgen05.ld.sync.aligned.32x32b.x32.b32 {%0,%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30,%31},[%32];"
        :"=r"(d[0]),"=r"(d[1]),"=r"(d[2]),"=r"(d[3]),"=r"(d[4]),"=r"(d[5]),"=r"(d[6]),"=r"(d[7]),
         "=r"(d[8]),"=r"(d[9]),"=r"(d[10]),"=r"(d[11]),"=r"(d[12]),"=r"(d[13]),"=r"(d[14]),"=r"(d[15]),
         "=r"(d[16]),"=r"(d[17]),"=r"(d[18]),"=r"(d[19]),"=r"(d[20]),"=r"(d[21]),"=r"(d[22]),"=r"(d[23]),
         "=r"(d[24]),"=r"(d[25]),"=r"(d[26]),"=r"(d[27]),"=r"(d[28]),"=r"(d[29]),"=r"(d[30]),"=r"(d[31])
        :"r"(col));
    asm volatile("tcgen05.wait::ld.sync.aligned;");
}
template<int N> __device__ __forceinline__ void tmem_st_32dp(uint32_t col,const float*in);
template<> __device__ __forceinline__ void tmem_st_32dp<32>(uint32_t col,const float*in){
    const uint32_t*d=(const uint32_t*)in;
    cute::SM100_TMEM_STORE_32dp32b32x::copy(d[0],d[1],d[2],d[3],d[4],d[5],d[6],d[7],
        d[8],d[9],d[10],d[11],d[12],d[13],d[14],d[15],
        d[16],d[17],d[18],d[19],d[20],d[21],d[22],d[23],
        d[24],d[25],d[26],d[27],d[28],d[29],d[30],d[31],col);
    cutlass::arch::fence_view_async_tmem_store();
}
// ---- Layouts ----
using SmemLayoutQ = decltype(coalesce(tile_to_shape(UMMA::Layout_K_SW128_Atom<bf16_t>{},Shape<Int<B_H>,Int<D_QK>>{},Step<_1,_2>{}),Shape<_1,_1>{}));
template<int T> using SmemLayoutK_SW128 = decltype(coalesce(tile_to_shape(UMMA::Layout_K_SW128_Atom<bf16_t>{},Shape<Int<B_H>,Int<64*T>>{},Step<_1,_2>{}),Shape<_1,_1>{}));
template<int T> using SmemLayoutK_DG_SW128 = decltype(coalesce(tile_to_shape(UMMA::Layout_K_SW128_Atom<bf16_t>{},Shape<Int<B_H*2>,Int<64*T>>{},Step<_1,_2>{}),Shape<_1,_1>{}));
using SmemLayoutS = decltype(tile_to_shape(UMMA::Layout_K_INTER_Atom<bf16_t>{},Shape<Int<B_H>,Int<B_TOPK>>{},Step<_1,_2>{}));
template<int T> using SmemLayoutKT_SW128 = decltype(composition(SmemLayoutK_SW128<T>{},Layout<Shape<Int<64*T>,Int<B_TOPK>>,Stride<Int<B_TOPK>,_1>>{}));
// MMA types: QK = TS dual gemm, SV = SS
using TiledMMA_P = decltype(make_tiled_mma(SM100_MMA_F16BF16_WS_TS_NOELECT<bf16_t,bf16_t,float,B_H,B_TOPK*2,UMMA::Major::K,UMMA::Major::K>{}));
using TiledMMA_O = decltype(make_tiled_mma(SM100_MMA_F16BF16_WS_SS_NOELECT<bf16_t,bf16_t,float,B_H,256,UMMA::Major::K,UMMA::Major::MN>{}));
// TMEM columns
struct TC { static constexpr int O=0, Q=256, P=400; };
// ---- SMEM Plan ----
struct alignas(128) SmemPlan {
    union {
        struct { bf16_t q[cosize_v<SmemLayoutQ>]; union { bf16_t o_buf[B_H*D_V]; float o_accum[B_H*520]; }; } qo;
        struct { struct { bf16_t nope[cosize_v<SmemLayoutK_SW128<D_NOPE/64>>]; bf16_t rope[cosize_v<SmemLayoutK_SW128<1>>]; } dequant[NUM_BUFS];
            e4m3_t raw_nope[NUM_BUFS][B_H*D_NOPE]; } kv;
    } u;
    union { float4 p_xchg[4][16*B_TOPK/4]; bf16_t s[cosize_v<SmemLayoutS>]; } sp;
    alignas(16) float rowmax[128];
    char is_valid[NUM_INDEX_BUFS][B_TOPK/8];
    int tma_coord[NUM_INDEX_BUFS][B_TOPK];
    uint8_t scales[NUM_INDEX_BUFS][B_TOPK][NUM_SCALES_EACH];
    alignas(16) uint32_t tmem_addr;
    alignas(8) uint64_t bar_last_store;
    alignas(8) uint64_t bar_q_tma, bar_q_utccp;
    alignas(8) uint64_t bar_rope_ready[NUM_BUFS], bar_nope_ready[NUM_BUFS];
    alignas(8) uint64_t bar_raw_ready[NUM_BUFS], bar_raw_free[NUM_BUFS];
    alignas(8) uint64_t bar_vcs_ready[NUM_INDEX_BUFS], bar_vcs_free[NUM_INDEX_BUFS];
    alignas(8) uint64_t bar_qk_done[NUM_BUFS], bar_so_ready[NUM_BUFS], bar_sv_done[NUM_BUFS];
};
void chk(cudaError_t e,const char*m){if(e!=cudaSuccess){fprintf(stderr,"CUDA(%s):%s\n",m,cudaGetErrorString(e));exit(1);}}
void chk(CUresult e,const char*m){if(e!=CUDA_SUCCESS){const char*s;cuGetErrorString(e,&s);fprintf(stderr,"CU(%s):%s\n",m,s);exit(1);}}
// ---- Ring state for double buffering ----
struct RS { int bi=0; bool bp=0; int ii=0; bool ip=0;
    __device__ void upd(){ bp^=(bi==NUM_BUFS-1); bi=(bi+1)%NUM_BUFS; ip^=(ii==NUM_INDEX_BUFS-1); ii=(ii+1)%NUM_INDEX_BUFS; }};
// ---- Scheduler ----
__global__ void __launch_bounds__(32,1,1)
my_sched_kernel(__grid_constant__ const GetDecodeSchedMetaParams params){
    int bs=params.b,bn=params.block_size_n,fo=params.fixed_overhead_num_blocks,np=params.num_sm_parts;
    extern __shared__ int sm[];int*nb_s=sm,*ns_s=sm+bs,*sk_s=sm+bs*2+1,*fb_s=sm+bs*3+1,*lb_s=sm+bs*4+1;
    int total=0;
    for(int i=threadIdx.x;i<bs;i+=32){int sk=params.topk_length?__ldg(params.topk_length+i):params.topk;if(sk==0)sk=1;
        if(params.extra_topk){sk=((sk+bn-1)/bn)*bn;sk+=params.extra_topk_length?__ldg(params.extra_topk_length+i):params.extra_topk;}
        sk_s[i]=sk;int fb=0,lb=max(sk-1,0)/bn;int n=lb-fb+1;total+=n+fo;nb_s[i]=n;fb_s[i]=fb;lb_s[i]=lb;}
    for(int o=16;o>=1;o>>=1)total+=__shfl_xor_sync(0xFFFFFFFF,total,o);__syncwarp();
    if(threadIdx.x==0){int pay=(total+np-1)/np+fo,nr=0,nb=0,ns=0,cum=0;ns_s[0]=0;
        for(int i=0;i<np;i++){DecodingSchedMeta m;m.begin_req_idx=nr;m.begin_block_idx=nb+fb_s[nr];m.begin_split_idx=ns;m.is_first_req_splitted=(nb!=0);
            int rem=pay;while(nr<bs){int n2=nb_s[nr]-nb;if(rem>=n2+fo){cum+=ns+1;ns_s[nr+1]=cum;rem-=n2+fo;nr++;nb=0;ns=0;}else{if(rem-fo>0){nb+=rem-fo;ns++;rem=0;}break;}}
            m.end_req_idx=nb>0?nr:nr-1;m.end_block_idx=nb>0?nb+fb_s[nr]:(sk_s[nr-1]==0?0:lb_s[nr-1]+1);
            m.is_last_req_splitted=m.end_block_idx!=lb_s[m.end_req_idx]+1&&sk_s[m.end_req_idx]!=0;
            if(m.begin_req_idx==m.end_req_idx)m.is_first_req_splitted=m.is_last_req_splitted=m.is_first_req_splitted||m.is_last_req_splitted;
            params.tile_scheduler_metadata_ptr[i]=m;}}
    __syncwarp();for(int i=threadIdx.x;i<=bs;i+=32)params.num_splits_ptr[i]=ns_s[i];}
// ---- Combine ----
template<int DV,int BM,int MS>__global__ void __launch_bounds__(BM*32)
my_combine_kernel(__grid_constant__ const CombineParams p){
    int bi=blockIdx.x,si=blockIdx.y,hb=blockIdx.z,wi=threadIdx.x/32,li=threadIdx.x%32;
    if(wi>=min(BM,p.h_q-BM*hb))return;int ss=__ldg(p.num_splits_ptr+bi),se=__ldg(p.num_splits_ptr+bi+1),ns=se-ss;if(ns==1)return;
    constexpr int E=DV/128;float*oap=p.o_accum+ss*p.stride_o_accum_split+si*p.stride_o_accum_s_q+(hb*BM+wi)*p.stride_o_accum_h_q;
    float4 d[E];for(int i=0;i<E;i++)d[i]=*(float4*)(oap+li*4+i*128);__shared__ float sb[BM][MS];
    float*lp=(float*)p.lse_accum+ss*p.stride_lse_accum_split+si*p.stride_lse_accum_s_q+hb*BM;
    constexpr int L=(MS+31)/32;float ll[L];for(int i=0;i<L;i++){int s=i*32+li;ll[i]=s<ns?*(lp+s*p.stride_lse_accum_split+wi):-INFINITY;}
    float mx=-INFINITY;for(int i=0;i<L;i++)mx=fmaxf(mx,ll[i]);for(int o=16;o>=1;o>>=1)mx=fmaxf(mx,__shfl_xor_sync(0xFFFFFFFF,mx,o));if(mx==-INFINITY)mx=0.0f;
    float sm=0;for(int i=0;i<L;i++)sm+=exp2f(ll[i]-mx);for(int o=16;o>=1;o>>=1)sm+=__shfl_xor_sync(0xFFFFFFFF,sm,o);
    float gl=(sm==0.f||sm==-INFINITY)?INFINITY:log2f(sm)+mx;if(li==0)*((float*)p.lse+bi*p.stride_lse_b+si*p.stride_lse_s_q+hb*BM+wi)=gl/1.4426950408889634f;
    for(int i=0;i<L;i++){int s=i*32+li;sb[wi][s]=exp2f(ll[i]-gl);}__syncwarp();
    float4 r[E];for(int i=0;i<E;i++)r[i]={0,0,0,0};
    for(int sp2=0;sp2<ns;sp2++){float sc=sb[wi][sp2];for(int i=0;i<E;i++){r[i].x+=sc*d[i].x;r[i].y+=sc*d[i].y;r[i].z+=sc*d[i].z;r[i].w+=sc*d[i].w;if(sp2!=ns-1)d[i]=*(float4*)(oap+(sp2+1)*p.stride_o_accum_split+li*4+i*128);}}
    bf16_t*op=(bf16_t*)p.out+bi*p.stride_o_b+si*p.stride_o_s_q+(hb*BM+wi)*p.stride_o_h_q;
    for(int i=0;i<E;i++){__nv_bfloat162 a=__float22bfloat162_rn({r[i].x,r[i].y}),b=__float22bfloat162_rn({r[i].z,r[i].w});*(uint32_t*)(op+li*4+i*128)=*(uint32_t*)&a;*(uint32_t*)(op+li*4+i*128+2)=*(uint32_t*)&b;}}
// ---- Validation ----
__global__ void mla_validate(const __nv_bfloat16*Q,const uint8_t*kvm,const int*im,const uint8_t*kve,const int*ie,__nv_bfloat16*Out,float*LSE,
    int B,int SQ,int HQ,int tm,int te,int mbs,int ebs,int mst,int est,int sqb,int sqsq,int sqhq,int simb,int simsq,int sieb,int siesq,int sob,int sosq,int sohq,int slb,int slsq,float sms){
    int bsq=blockIdx.x,hg=blockIdx.y,bi=bsq/SQ,si=bsq%SQ,tid=threadIdx.x;if(bi>=B||hg>=HQ)return;
    const __nv_bfloat16*qp=Q+bi*sqb+si*sqsq+hg*sqhq;float q[D_QK];for(int d=tid;d<D_QK;d+=blockDim.x)q[d]=__bfloat162float(qp[d]);
    float mi=-1e30f,li=0;float acc[D_V];for(int d=tid;d<D_V;d+=blockDim.x)acc[d]=0;
    for(int t=0;t<tm+te;t++){int ti;const uint8_t*kb;int bs2,st;if(t<tm){ti=im[bi*simb+si*simsq+t];kb=kvm;bs2=mbs;st=mst;}else{ti=ie[bi*sieb+si*siesq+(t-tm)];kb=kve;bs2=ebs;st=est;}if(ti==-1)continue;
        int pi=(unsigned)ti/bs2,ii=(unsigned)ti%bs2;const uint8_t*bb=kb+(int64_t)pi*st,*nf=bb+ii*(D_NOPE+2*D_ROPE);const __nv_bfloat16*rb=(const __nv_bfloat16*)(nf+D_NOPE);const uint8_t*sc=bb+bs2*(D_NOPE+2*D_ROPE)+ii*8;
        float dot=0;for(int d=tid;d<D_QK;d+=blockDim.x){float kv;if(d<D_NOPE){uint8_t ue=sc[d/QUANT_TILE];float sv=(ue!=0)?__int_as_float((uint32_t)ue<<23):0;kv=__half2float(__nv_cvt_fp8_to_halfraw(nf[d],__NV_E4M3))*sv;}else kv=__bfloat162float(rb[d-D_NOPE]);dot+=q[d]*kv;}
        for(int o=16;o>0;o>>=1)dot+=__shfl_xor_sync(0xFFFFFFFF,dot,o);__shared__ float sd[32];int wi=tid/32,l2=tid%32;if(l2==0)sd[wi]=dot;__syncthreads();if(wi==0){dot=(l2<blockDim.x/32)?sd[l2]:0;for(int o=16;o>0;o>>=1)dot+=__shfl_xor_sync(0xFFFFFFFF,dot,o);}__syncthreads();if(tid==0)sd[0]=dot;__syncthreads();
        float score=sd[0]*sms,nm=fmaxf(mi,score),os=expf(mi-nm),p=expf(score-nm);
        for(int d=tid;d<D_V;d+=blockDim.x){float kv;if(d<D_NOPE){uint8_t ue=sc[d/QUANT_TILE];float sv=(ue!=0)?__int_as_float((uint32_t)ue<<23):0;kv=__half2float(__nv_cvt_fp8_to_halfraw(nf[d],__NV_E4M3))*sv;}else kv=__bfloat162float(rb[d-D_NOPE]);acc[d]=acc[d]*os+p*kv;}mi=nm;li=li*os+p;__syncthreads();}
    float il=(li>0)?1.0f/li:0;__nv_bfloat16*op=Out+bi*sob+si*sosq+hg*sohq;for(int d=tid;d<D_V;d+=blockDim.x)op[d]=__float2bfloat16(acc[d]*il);if(tid==0){float lv=(li>0)?(mi+logf(li)):INFINITY;LSE[bi*slb+si*slsq+hg]=lv;}}
// ======== MAIN ATTENTION KERNEL (3 warpgroups) ========
__global__ void __launch_bounds__(NUM_THREADS, 1, 1)
my_attn_kernel_v3(
    __grid_constant__ const CUtensorMap tmap_nope_main, __grid_constant__ const CUtensorMap tmap_nope_extra,
    __grid_constant__ const CUtensorMap tmap_rope_main, __grid_constant__ const CUtensorMap tmap_rope_extra,
    __grid_constant__ const CUtensorMap tmap_q_sw128,
    const __nv_bfloat16*__restrict__ Q, const int*__restrict__ im, const int*__restrict__ ie,
    float*__restrict__ oa, float*__restrict__ la, __nv_bfloat16*__restrict__ Out, float*__restrict__ LSE,
    const DecodingSchedMeta*__restrict__ sched, const int*__restrict__ nsplits,
    int B,int SQ,int HQ,int topk,int etopk,int mbs,int ebs,int64_t mst64,int64_t est64,
    int sqb,int sqsq,int sqhq, int sib,int sisq,int seib,int seisq,
    int sob,int sosq,int sohq, int slb,int slsq,
    int soas,int soasq,int soahq, int slas,int slasq, float sml2,
    int tma_step_main, int tma_step_extra,
    const uint8_t*__restrict__ kv_scales_main, const uint8_t*__restrict__ kv_scales_extra,
    __grid_constant__ const CUtensorMap tmap_o_store)
{
#if defined(__CUDA_ARCH__) && (__CUDA_ARCH__ >= 1000)
    const int sqx=blockIdx.x, pidx=blockIdx.y, hgidx=blockIdx.z;
    const int head_off=hgidx*B_H;
    const int wg=threadIdx.x/128, iwg=threadIdx.x%128;
    const int warp=threadIdx.x/32, lane=threadIdx.x%32;
    extern __shared__ char smem_raw[];
    auto& plan = *reinterpret_cast<SmemPlan*>(smem_raw);
    // Init
    if(warp==0 && elect()){
        asm volatile("prefetch.tensormap [%0];":: "l"(&tmap_nope_main));
        asm volatile("prefetch.tensormap [%0];":: "l"(&tmap_nope_extra));
        asm volatile("prefetch.tensormap [%0];":: "l"(&tmap_rope_main));
        asm volatile("prefetch.tensormap [%0];":: "l"(&tmap_rope_extra));
        asm volatile("prefetch.tensormap [%0];":: "l"(&tmap_q_sw128));
        asm volatile("prefetch.tensormap [%0];":: "l"(&tmap_o_store));
    }
    if(warp==0){
        if(elect()){
            bar_init(&plan.bar_last_store,128);
            bar_init(&plan.bar_q_tma,1); bar_init(&plan.bar_q_utccp,1);
            for(int i=0;i<NUM_BUFS;i++){
                bar_init(&plan.bar_rope_ready[i],1);
                bar_init(&plan.bar_nope_ready[i],128);
                bar_init(&plan.bar_raw_ready[i],1);
                bar_init(&plan.bar_raw_free[i],128);
                bar_init(&plan.bar_qk_done[i],1);
                bar_init(&plan.bar_so_ready[i],128);
                bar_init(&plan.bar_sv_done[i],1);
            }
            for(int i=0;i<NUM_INDEX_BUFS;i++){
                bar_init(&plan.bar_vcs_ready[i],32);
                bar_init(&plan.bar_vcs_free[i],128+128+1+1);
            }
            asm volatile("fence.mbarrier_init.release.cluster;");
        }
        cute::TMEM::Allocator1Sm().allocate(512, &plan.tmem_addr);
        cute::TMEM::Allocator1Sm().release_allocation_lock();
    }
    __syncthreads();
    // Read sched meta
    DecodingSchedMeta meta;{const uint64_t*s=(const uint64_t*)(sched+pidx);uint64_t*d=(uint64_t*)&meta;d[0]=__ldg(s);d[1]=__ldg(s+1);d[2]=__ldg(s+2);d[3]=__ldg(s+3);}
    if(meta.begin_req_idx>=B){ if(warp==0)cute::TMEM::Allocator1Sm().free(0,512); return; }
    struct MLArgs { int bi,sb,eb; bool nosplit; int nsi; bool bpb; int tl,etl,nob; bool last; };
    auto make_args=[&](int bi,bool bpb)->MLArgs{
        int tl=topk, etl=etopk;
        int op2=max(((tl+B_TOPK-1)/B_TOPK)*(int)B_TOPK,(int)B_TOPK);
        int tp=op2+((etl+B_TOPK-1)/B_TOPK)*B_TOPK;
        int sb2=(bi==meta.begin_req_idx)?meta.begin_block_idx:0;
        int eb2=(bi==meta.end_req_idx)?meta.end_block_idx:tp/B_TOPK;
        bool isp=(bi==meta.begin_req_idx)?meta.is_first_req_splitted:((bi==meta.end_req_idx)?meta.is_last_req_splitted:false);
        int nsi2=(bi==meta.begin_req_idx)?(__ldg(nsplits+bi)+meta.begin_split_idx):__ldg(nsplits+bi);
        return {bi,sb2,eb2,!isp,nsi2,bpb,tl,etl,op2/B_TOPK,bi==meta.end_req_idx};
    };
    RS rs;
    const int64_t L2_HINT = 2; // EVICT_LAST
    if(wg==0){
        // ======== WG0: Softmax + Scale O + Epilogue ========
        cutlass::arch::warpgroup_reg_alloc<200>();
        auto sS = make_tensor(make_smem_ptr(plan.sp.s), SmemLayoutS{});
        bf16_t* sS_base = &sS(lane*1,0) - lane + lane*8 + (warp&1)*(B_H/2)*8 + (warp/2)*B_H*(B_TOPK/2);
        // Actually compute sS_base properly:
        sS_base = (bf16_t*)plan.sp.s + lane*8 + (warp&1)*(B_H/2)*8 + (warp/2)*B_H*(B_TOPK/2);
        const float2 scale2 = {sml2, sml2};
        bool bpb = false;
        #pragma unroll 1
        for(int bi=meta.begin_req_idx; bi<=meta.end_req_idx; bi++, bpb^=1){
            auto args = make_args(bi, bpb);
            // Wait for previous batch's TMA/bulk stores before signal
            asm volatile("cp.async.bulk.wait_group 0;");
            bar_arrive(&plan.bar_last_store);
            float mi = MAX_INIT_VAL, li = 0.0f, real_mi = -INFINITY;
            #pragma unroll 1
            for(int blk=args.sb; blk<args.eb; blk++){
                named_bar_sync(nb_wg0_sync, 128);
                bar_wait(&plan.bar_vcs_ready[rs.ii], rs.ip);
                bar_wait(&plan.bar_qk_done[rs.bi], rs.bp);
                asm volatile("tcgen05.fence::after_thread_sync;");
                // Load P from TMEM
                float p[B_TOPK/2], p_peer[B_TOPK/2];
                if(warp<2){
                    tmem_ld_32dp<32>(TC::P, p);
                    tmem_ld_32dp<32>(TC::P+32, p_peer);
                } else {
                    tmem_ld_32dp<32>(TC::P, p_peer);
                    tmem_ld_32dp<32>(TC::P+32, p);
                }
                asm volatile("tcgen05.fence::before_thread_sync;");
                cutlass::arch::fence_view_async_tmem_load();
                // P exchange: warp0↔warp2, warp1↔warp3
                #pragma unroll
                for(int i=0;i<(B_TOPK/2)/4;i++)
                    plan.sp.p_xchg[warp^2][i*32+lane]=*(float4*)(p_peer+i*4);
                named_bar_sync(nb_wg0_w02+(warp&1), 64);
                #pragma unroll
                for(int i=0;i<(B_TOPK/2)/4;i++){
                    float2 t[2]; *(float4*)t=plan.sp.p_xchg[warp][i*32+lane];
                    float2*cp=(float2*)(p+i*4); cp[0]=f2add(cp[0],t[0]); cp[1]=f2add(cp[1],t[1]);
                }
                // Mask
                uint32_t vmask=*((uint32_t*)plan.is_valid[rs.ii]+(iwg>=64?1:0));
                #pragma unroll
                for(int i=0;i<B_TOPK/2;i++) if(!(vmask>>i&1)) p[i]=-INFINITY;
                // Rowwise max
                float cur_max=-INFINITY;
                #pragma unroll
                for(int i=0;i<B_TOPK/2;i++) cur_max=fmaxf(cur_max,p[i]);
                cur_max *= sml2;
                plan.rowmax[iwg] = cur_max;
                named_bar_sync(nb_wg0_sync, 128);
                bar_arrive(&plan.bar_vcs_free[rs.ii]);
                cur_max = fmaxf(cur_max, plan.rowmax[iwg^64]);
                real_mi = fmaxf(real_mi, cur_max);
                bool should_scale = __any_sync(0xFFFFFFFF, cur_max - mi > 6.0f);
                float new_max, scale_old;
                if(!should_scale){ scale_old=1.0f; new_max=mi; }
                else { new_max=fmaxf(cur_max,mi); scale_old=exp2f(mi-new_max); }
                mi = new_max;
                // Calc S
                __nv_bfloat162 sv[(B_TOPK/2)/2];
                float2 neg_nm={-new_max,-new_max}, cur_sum={0,0};
                #pragma unroll
                for(int i=0;i<(B_TOPK/2)/2;i++){
                    float2 d2=f2fma(float2{p[i*2],p[i*2+1]},scale2,neg_nm);
                    d2.x=exp2f(d2.x); d2.y=exp2f(d2.y);
                    cur_sum=f2add(cur_sum,d2);
                    sv[i]=__float22bfloat162_rn(d2);
                }
                li=fmaf(li,scale_old,cur_sum.x+cur_sum.y);
                // Write S
                #pragma unroll
                for(int i=0;i<B_TOPK/2/8;i++)
                    *(__int128_t*)(sS_base+B_H*8*i)=*(__int128_t*)(sv+i*4);
                // Scale O in TMEM
                if(blk!=args.sb && should_scale){
                    float2 sf2={scale_old,scale_old};
                    asm volatile("tcgen05.fence::after_thread_sync;");
                    constexpr int CS=64;
                    float2 ov[CS/2];
                    #pragma unroll 1
                    for(int ci=0;ci<(D_V/2)/CS;ci++){
                        tmem_ld_32dp<32>(TC::O+ci*CS, (float*)ov);
                        cutlass::arch::fence_view_async_tmem_load();
                        #pragma unroll
                        for(int j=0;j<CS/2;j++) ov[j]=f2mul(ov[j],sf2);
                        tmem_st_32dp<32>(TC::O+ci*CS, (const float*)ov);
                        asm volatile("tcgen05.fence::before_thread_sync;");
                    }
                    asm volatile("tcgen05.fence::before_thread_sync;");
                }
                cutlass::arch::fence_view_async_shared();
                bar_arrive(&plan.bar_so_ready[rs.bi]);
                if(blk!=args.eb-1) rs.upd();
            }
            if(real_mi==-INFINITY){li=0;mi=-INFINITY;}
            // Exchange li
            plan.rowmax[iwg]=li;
            named_bar_sync(nb_wg0_sync,128);
            li+=plan.rowmax[iwg^64];
            // Store LSE
            if(iwg<B_H){
                if(args.nosplit){
                    float cur_lse=fmaf(mi,0.6931471805599453f,logf(li)); // mi*ln2 + log(li)
                    if(cur_lse==-INFINITY)cur_lse=INFINITY;
                    float*gLSE=(float*)LSE+args.bi*slb+sqx*slsq+head_off+iwg;
                    *gLSE=cur_lse;
                } else {
                    float cur_lse=log2f(li)+mi;
                    float*gLA=(float*)la+args.nsi*slas+sqx*slasq+head_off+iwg;
                    *gLA=cur_lse;
                }
            }
            // Wait last SV done
            bar_wait(&plan.bar_sv_done[rs.bi], rs.bp);
            rs.upd();
            asm volatile("tcgen05.fence::after_thread_sync;");
            // Signal PDL completion for last batch to allow overlapping launches
            if(args.last) cudaTriggerProgrammaticLaunchCompletion();
            // Epilogue: read O from TMEM, scale, write out
            float o_scale = (li==0)?0:__fdividef(1.0f,li);
            float2 o_sf2={o_scale,o_scale};
            if(args.nosplit){
                // Pipelined epilogue: TMEM→bf16→SW128 SMEM per chunk, TMA store interleaved
                constexpr int BE=64;
                auto sObuf=make_tensor(make_smem_ptr(plan.u.qo.o_buf),tile_to_shape(UMMA::Layout_K_SW128_Atom<bf16_t>{},Shape<Int<B_H>,Int<D_V>>{}));
                bf16_t*sO_bases[BE/8];
                #pragma unroll
                for(int k=0;k<BE/8;k++) sO_bases[k]=&sObuf(iwg%64,(iwg/64)*128+k*8);
                auto sOtile=flat_divide(sObuf,Shape<Int<B_H>,Int<64>>{});
                #pragma unroll 1
                for(int i=0;i<(D_V/2)/BE;i++){
                    // Load from TMEM
                    float2 ov[BE/2];
                    tmem_ld_32dp<32>(TC::O+i*BE, (float*)ov);
                    cutlass::arch::fence_view_async_tmem_load();
                    // Scale & convert to bf16
                    __nv_bfloat162 o_bf16[BE/2];
                    #pragma unroll
                    for(int j=0;j<BE/2;j++){
                        ov[j]=f2mul(ov[j],o_sf2);
                        o_bf16[j]=__float22bfloat162_rn({ov[j].x,ov[j].y});
                    }
                    // Write bf16 to SW128 SMEM
                    int col_base=(i*BE>=D_V/4?D_V/2:0)+(i*BE%(D_V/4));
                    #pragma unroll
                    for(int j=0;j<BE/8;j++)
                        *(__int128_t*)(sO_bases[j]+col_base*(int)B_H)=*(__int128_t*)(o_bf16+j*4);
                    // Sync
                    cutlass::arch::fence_view_async_shared();
                    named_bar_sync(nb_wg0_sync, 128);
                    // TMA store (2 warps)
                    if(warp==0 && elect()){
                        uint32_t sa=cute::cast_smem_ptr_to_uint(&sOtile(_0{},_0{},_0{},col_base/64));
                        asm volatile("cp.async.bulk.tensor.4d.global.shared::cta.bulk_group [%0,{%1,%2,%3,%4}],[%5];"
                            ::"l"(&tmap_o_store),"r"(col_base),"r"((int)head_off),"r"(sqx),"r"(args.bi),"r"(sa):"memory");
                    }
                    if(warp==1 && elect()){
                        int col2=col_base+(D_V/4);
                        uint32_t sa=cute::cast_smem_ptr_to_uint(&sOtile(_0{},_0{},_0{},col2/64));
                        asm volatile("cp.async.bulk.tensor.4d.global.shared::cta.bulk_group [%0,{%1,%2,%3,%4}],[%5];"
                            ::"l"(&tmap_o_store),"r"(col2),"r"((int)head_off),"r"(sqx),"r"(args.bi),"r"(sa):"memory");
                    }
                }
                asm volatile("cp.async.bulk.commit_group;");
            } else {
                // Split case: TMEM→float→SMEM o_accum, then bulk copy S2G
                constexpr int BE=64;
                float2 ov[BE/2];
                float*sO = plan.u.qo.o_accum; // stride 520
                #pragma unroll 1
                for(int i=0;i<(D_V/2)/BE;i++){
                    tmem_ld_32dp<32>(TC::O+i*BE, (float*)ov);
                    cutlass::arch::fence_view_async_tmem_load();
                    #pragma unroll
                    for(int j=0;j<BE/2;j++) ov[j]=f2mul(ov[j],o_sf2);
                    int col_base = (iwg/64)*128 + (i*BE>=D_V/4?D_V/2:0)+(i*BE%(D_V/4));
                    #pragma unroll
                    for(int j=0;j<BE/4;j++)
                        *(__int128_t*)&sO[(iwg%64)*520+col_base+j*4]=*(__int128_t*)&ov[j*2];
                }
                cutlass::arch::fence_view_async_shared();
                named_bar_sync(nb_wg0_sync, 128);
                // Bulk copy S2G: each elected warp copies B_H/4 rows
                float*gOA=oa+args.nsi*soas+sqx*soasq+head_off*soahq;
                if(elect()){
                    #pragma unroll
                    for(int lr=0;lr<B_H/4;lr++){
                        int row=lr*4+warp;
                        uint32_t sa=cute::cast_smem_ptr_to_uint(&sO[row*520]);
                        asm volatile("cp.async.bulk.global.shared::cta.bulk_group [%0],[%1],%2;"
                            ::"l"((void*)(gOA+row*soahq)),"r"(sa),"r"((uint32_t)(D_V*4)):"memory");
                    }
                }
                asm volatile("cp.async.bulk.commit_group;");
            }
            asm volatile("tcgen05.fence::before_thread_sync;");
            // No everyone_sync - WG0 proceeds independently using mbarrier protocol
        }
        if(warp==0) cute::TMEM::Allocator1Sm().free(0,512);
    } else if(wg==1){
        // ======== WG1: MMA + TMA + Index (low regs) ========
        // FIX: All threads share a common batch loop with everyone_sync
        cutlass::arch::warpgroup_reg_dealloc<72>();
        const int w1=warp; // 4,5,6,7
        // elect() called once per warp at init; consistent for all batch iterations
        bool el = (w1<=6) ? elect() : true; // warps 4,5,6: elect; warp 7: all active
        bool bpb_wg1 = false;
        #pragma unroll 1
        for(int bi=meta.begin_req_idx;bi<=meta.end_req_idx;bi++,bpb_wg1^=1){
            auto args=make_args(bi,bpb_wg1);
            // Phase 1+2: TMA Q load + UTCCP (warp 4 elected only)
            if(w1==4 && el){
                // Wait for previous batch's epilogue stores to complete (SMEM union safety)
                bar_wait(&plan.bar_last_store, bpb_wg1);
                // Issue 8 TMA loads for Q (each 64xB_H bf16 tile with SW128)
                {
                    auto sQ = make_tensor(make_smem_ptr(plan.u.qo.q), SmemLayoutQ{});
                    auto tiled_sQ = flat_divide(sQ, Shape<Int<B_H>,Int<64>>{});
                    uint32_t ba = cute::cast_smem_ptr_to_uint(&plan.bar_q_tma);
                    #pragma unroll
                    for(int ti=0;ti<D_QK/64;ti++){
                        uint32_t sa = cute::cast_smem_ptr_to_uint(&tiled_sQ(_0{},_0{},_0{},ti));
                        asm volatile("cp.async.bulk.tensor.4d.shared::cta.global.mbarrier::complete_tx::bytes.cta_group::1.L2::cache_hint [%0],[%1,{%2,%3,%4,%5}],[%6],%7;"
                            ::"r"(sa),"l"(&tmap_q_sw128),"r"(ti*64),"r"(head_off),"r"(sqx),"r"(args.bi),"r"(ba),"l"((int64_t)1):"memory");
                    }
                }
                bar_arrive_tx(&plan.bar_q_tma, B_H*D_QK*2);
                bar_wait(&plan.bar_q_tma, bpb_wg1);
                asm volatile("tcgen05.fence::after_thread_sync;");
                {
                    auto sQ_desc = UMMA::make_umma_desc<UMMA::Major::K>(
                        make_tensor(make_smem_ptr(plan.u.qo.q),
                            tile_to_shape(UMMA::Layout_K_SW128_Atom<bf16_t>{},Shape<Int<B_H*2>,Int<64>>{})));
                    #pragma unroll
                    for(int ti=0;ti<D_QK/128;ti++){
                        #pragma unroll
                        for(int si=0;si<64/16;si++){
                            SM100_UTCCP_128dp256bit_1cta::copy(
                                sQ_desc+(ti*(B_H*128)+si*16)*2/16,
                                TC::Q+ti*32+si*8);
                        }
                    }
                }
                umma_arrive_bar(&plan.bar_q_utccp);
            }
            // Phase 3: Warp-specialized block loops
            if(w1==4 && el){
                TiledMMA_P mma_p; TiledMMA_O mma_o;
                auto tP = partition_fragment_C(mma_p, Shape<Int<B_H>,_128>{});
                auto tO = partition_fragment_C(mma_o, Shape<Int<B_H>,Int<D_V>>{});
                tP.data().get() = TC::P;
                tO.data().get() = TC::O;
                bar_wait(&plan.bar_q_utccp, bpb_wg1);
                asm volatile("tcgen05.fence::after_thread_sync;");
                auto tQ = mma_p.get_slice(_0{}).make_fragment_A(
                    partition_shape_A(mma_p, Shape<Int<B_H>,Int<D_QK/2>>{}));
                tQ.data().get() = TC::Q;
                #pragma unroll 1
                for(int blk=args.sb;blk<args.eb;blk++){
                    bar_wait(&plan.bar_rope_ready[rs.bi], rs.bp);
                    bar_wait(&plan.bar_nope_ready[rs.bi], rs.bp);
                    asm volatile("tcgen05.fence::after_thread_sync;");
                    {auto sK=make_tensor(make_smem_ptr(plan.u.kv.dequant[rs.bi].nope),SmemLayoutK_DG_SW128<D_QK/64/2>{});
                    myutils::utcmma_ts(mma_p, tQ, sK, tP, true);}
                    umma_arrive_bar(&plan.bar_qk_done[rs.bi]);
                    bar_wait(&plan.bar_so_ready[rs.bi], rs.bp);
                    asm volatile("tcgen05.fence::after_thread_sync;");
                    {auto sS2=make_tensor(make_smem_ptr(plan.sp.s),SmemLayoutS{});
                    auto sV=make_tensor(make_smem_ptr(plan.u.kv.dequant[rs.bi].nope),SmemLayoutKT_SW128<D_V/64>{});
                    myutils::utcmma_ss(mma_o, sS2, sV, tO, blk==args.sb);}
                    umma_arrive_bar(&plan.bar_sv_done[rs.bi]);
                    rs.upd();
                }
            } else if(w1==5 && el){
                // NoPE TMA warp
                bar_wait(&plan.bar_q_utccp, bpb_wg1);
                bar_wait(&plan.bar_last_store, bpb_wg1);
                #pragma unroll 1
                for(int blk=args.sb;blk<args.eb;blk++){
                    bar_wait(&plan.bar_vcs_ready[rs.ii], rs.ip);
                    bar_wait(&plan.bar_raw_free[rs.bi], rs.bp^1);
                    const void*desc=(blk>=args.nob)?&tmap_nope_extra:&tmap_nope_main;
                    int4 ci=*(int4*)(plan.tma_coord[rs.ii]+0);
                    #pragma unroll
                    for(int row=0;row<B_TOPK;row+=4){
                        int4 ni; if(row+4<B_TOPK) ni=*(int4*)(plan.tma_coord[rs.ii]+row+4);
                        tma_gather4(desc,&plan.bar_raw_ready[rs.bi],
                            plan.u.kv.raw_nope[rs.bi]+D_NOPE*row, 0, ci, L2_HINT);
                        ci=ni;
                    }
                    bar_arrive_tx(&plan.bar_raw_ready[rs.bi], B_TOPK*D_NOPE);
                    bar_arrive(&plan.bar_vcs_free[rs.ii]);
                    rs.upd();
                }
            } else if(w1==6 && el){
                // RoPE TMA warp
                bar_wait(&plan.bar_q_utccp, bpb_wg1);
                bar_wait(&plan.bar_last_store, bpb_wg1);
                #pragma unroll 1
                for(int blk=args.sb;blk<args.eb;blk++){
                    bar_wait(&plan.bar_vcs_ready[rs.ii], rs.ip);
                    bar_wait(&plan.bar_sv_done[rs.bi], rs.bp^1);
                    const void*desc=(blk>=args.nob)?&tmap_rope_extra:&tmap_rope_main;
                    int4 ci=*(int4*)(plan.tma_coord[rs.ii]+0);
                    #pragma unroll
                    for(int row=0;row<B_TOPK;row+=4){
                        int4 ni; if(row+4<B_TOPK) ni=*(int4*)(plan.tma_coord[rs.ii]+row+4);
                        tma_gather4(desc,&plan.bar_rope_ready[rs.bi],
                            plan.u.kv.dequant[rs.bi].rope+64*row, 0, ci, L2_HINT);
                        ci=ni;
                    }
                    bar_arrive_tx(&plan.bar_rope_ready[rs.bi], B_TOPK*D_ROPE*2);
                    bar_arrive(&plan.bar_vcs_free[rs.ii]);
                    rs.upd();
                }
            } else if(w1==7){
                // Index transform warp (32 threads)
                int*idx_m=(int*)im+args.bi*sib+sqx*sisq;
                int*idx_e=(int*)ie+args.bi*seib+sqx*seisq;
                auto process_block=[&](int blk, bool is_extra){
                    int cbs=is_extra?ebs:mbs;
                    int cur_tma_step=is_extra?tma_step_extra:tma_step_main;
                    const uint8_t*cur_scales=is_extra?kv_scales_extra:kv_scales_main;
                    int64_t cur_stride=is_extra?est64:mst64;
                    int abs_pos; int my_idx[2];
                    if(!is_extra){
                        abs_pos=blk*B_TOPK+lane*2;
                        *(int2*)my_idx=__ldg((int2*)(idx_m+abs_pos));
                    } else {
                        abs_pos=(blk-args.nob)*B_TOPK+lane*2;
                        *(int2*)my_idx=__ldg((int2*)(idx_e+abs_pos));
                    }
                    bar_wait(&plan.bar_vcs_free[rs.ii], rs.ip^1);
                    int tc[2]; uint8_t sc[2*NUM_SCALES_EACH]; char vm=0;
                    #pragma unroll
                    for(int i=0;i<2;i++){
                        int blk_idx=(unsigned)my_idx[i]/cbs;
                        int idx_in=(unsigned)my_idx[i]%cbs;
                        bool valid=my_idx[i]!=-1 && (abs_pos+i<(is_extra?args.etl:args.tl));
                        vm|=valid<<i;
                        tc[i]=valid?blk_idx*cur_tma_step+idx_in:-1;
                        int64_t soff=blk_idx*cur_stride+idx_in*8;
                        uint64_t sx8=valid?__ldg((uint64_t*)(cur_scales+soff)):0;
                        *(uint64_t*)(sc+i*NUM_SCALES_EACH)=sx8;
                    }
                    vm<<=lane%4*2;
                    vm|=__shfl_xor_sync(0xFFFFFFFF,vm,1);
                    vm|=__shfl_xor_sync(0xFFFFFFFF,vm,2);
                    *(__int128_t*)(plan.scales[rs.ii]+lane*2)=*(__int128_t*)sc;
                    *(int2*)(plan.tma_coord[rs.ii]+lane*2)=*(int2*)tc;
                    if(lane%4==0) plan.is_valid[rs.ii][lane/4]=vm;
                    __syncwarp();
                    bar_arrive(&plan.bar_vcs_ready[rs.ii]);
                    rs.upd();
                };
                #pragma unroll 1
                for(int blk=args.sb;blk<min(args.nob,args.eb);blk++) process_block(blk,false);
                #pragma unroll 1
                for(int blk=max(args.sb,args.nob);blk<args.eb;blk++) process_block(blk,true);
            }
            // No everyone_sync - WG1 proceeds independently using mbarrier protocol
        }
    } else {
        // ======== WG2: Dequant ========
        cutlass::arch::warpgroup_reg_alloc<208>();
        constexpr int GS=8, NG=128/GS, RPG=B_TOPK/NG, CPG=D_NOPE/(GS*8);
        int gi=iwg/GS, ig=iwg%GS;
        auto nope0=make_tensor(make_smem_ptr(plan.u.kv.dequant[0].nope),SmemLayoutK_SW128<D_NOPE/64>{});
        bf16_t*nb0=&nope0(gi,ig*8);
        bf16_t*nb1=nb0+(plan.u.kv.dequant[1].nope-plan.u.kv.dequant[0].nope);
        e4m3_t*rb0=plan.u.kv.raw_nope[0]+gi*D_NOPE+ig*8;
        e4m3_t*rb1=rb0+B_H*D_NOPE;
        bool bpb=false;
        #pragma unroll 1
        for(int bi=meta.begin_req_idx;bi<=meta.end_req_idx;bi++,bpb^=1){
            auto args=make_args(bi,bpb);
            bar_wait(&plan.bar_q_utccp, bpb);
            #pragma unroll 1
            for(int blk=args.sb;blk<args.eb;blk++){
                bar_wait(&plan.bar_vcs_ready[rs.ii], rs.ip);
                bar_wait(&plan.bar_raw_ready[rs.bi], rs.bp);
                bar_wait(&plan.bar_sv_done[rs.bi], rs.bp^1);
                uint32_t nba=cute::cast_smem_ptr_to_uint(rs.bi==0?nb0:nb1);
                e4m3_t*rb=rs.bi==0?rb0:rb1;
                #pragma unroll
                for(int lr=0;lr<RPG;lr++){
                    int ri=lr*NG+gi;
                    // Load scales
                    __nv_bfloat16 scales[8];
                    uint64_t se8=*(uint64_t*)plan.scales[rs.ii][ri];
                    uint8_t*se=(uint8_t*)&se8;
                    // Convert e8m0 to bf16 scales using hardware intrinsic
                    *(__nv_bfloat162_raw*)(scales+0) = __nv_cvt_e8m0x2_to_bf162raw(*(unsigned short*)(se+0));
                    *(__nv_bfloat162_raw*)(scales+2) = __nv_cvt_e8m0x2_to_bf162raw(*(unsigned short*)(se+2));
                    *(__nv_bfloat162_raw*)(scales+4) = __nv_cvt_e8m0x2_to_bf162raw(*(unsigned short*)(se+4));
                    *(__nv_bfloat162_raw*)(scales+6) = __nv_cvt_e8m0x2_to_bf162raw(*(unsigned short*)(se+6));
                    uint64_t fp8x8=*(uint64_t*)(rb+lr*NG*D_NOPE);
                    #pragma unroll
                    for(int lc=0;lc<CPG;lc++){
                        __nv_fp8x2_e4m3 df8[4];
                        *(uint64_t*)df8=fp8x8;
                        if(lc+1<CPG) fp8x8=*(uint64_t*)(rb+lr*NG*D_NOPE+(lc+1)*GS*8);
                        __nv_bfloat16 sc=scales[lc];
                        __nv_bfloat162 dbf[4];
                        #pragma unroll
                        for(int i=0;i<4;i++) dbf[i]=fp8x2_bf16x2_scale(df8[i],sc);
                        asm volatile("st.weak.shared::cta.b128 [%0],%1;"
                            ::"r"(nba+2*(lr*NG*64+lc*B_TOPK*64)),"q"(*(__int128_t*)dbf));
                    }
                }
                cutlass::arch::fence_view_async_shared();
                bar_arrive(&plan.bar_nope_ready[rs.bi]);
                bar_arrive(&plan.bar_raw_free[rs.bi]);
                bar_arrive(&plan.bar_vcs_free[rs.ii]);
                rs.upd();
            }
            // No everyone_sync - WG2 proceeds independently using mbarrier protocol
        }
    }
    // No final sync needed - each warpgroup handles its own sync
#endif
}
// ---- Host helpers ----
static float ue8m0f(uint8_t e){if(!e)return 0;uint32_t b=(uint32_t)e<<23;float v;memcpy(&v,&b,4);return v;}
static uint8_t f2ue8m0(float v){if(v<=0)return 0;float p=exp2f(roundf(log2f(v)));uint32_t b;memcpy(&b,&p,4);return(b>>23)&0xFF;}
static uint8_t f2fp8(float v){return(uint8_t)__nv_cvt_float_to_fp8(v,__NV_SATFINITE,__NV_E4M3);}
static void quantize_nope(const float*in,uint8_t*on,uint8_t*os,int dn){for(int t=0;t<NUM_SCALES;t++){int s=t*QUANT_TILE,e=std::min(s+QUANT_TILE,dn);float mx=0;for(int i=s;i<e;i++)mx=std::max(mx,fabsf(in[i]));float si=exp2f(ceilf(log2f(std::max(mx/448.0f,1e-4f))));os[t]=f2ue8m0(si);float iv=(ue8m0f(os[t])>0)?1.0f/ue8m0f(os[t]):0;for(int i=s;i<e;i++)on[i]=f2fp8(in[i]*iv);}os[NUM_SCALES]=0;}
static void dequant_tok(const uint8_t*bb,int idx,int bs,float*out){const uint8_t*nr=bb+idx*(D_NOPE+2*D_ROPE);const uint8_t*sc=bb+bs*(D_NOPE+2*D_ROPE)+idx*8;for(int t=0;t<NUM_SCALES;t++){float s=ue8m0f(sc[t]);for(int i=t*QUANT_TILE;i<std::min((t+1)*QUANT_TILE,(int)D_NOPE);i++)out[i]=__half2float(__nv_cvt_fp8_to_halfraw(nr[i],__NV_E4M3))*s;}const __nv_bfloat16*rp=(const __nv_bfloat16*)(nr+D_NOPE);for(int i=0;i<D_ROPE;i++)out[D_NOPE+i]=__bfloat162float(rp[i]);}
void gen_kv(uint8_t*d,int bs,std::mt19937&r){std::uniform_real_distribution<float>dist(-0.5f,0.5f);for(int t=0;t<bs;t++){float nv[D_NOPE];for(int i=0;i<D_NOPE;i++)nv[i]=dist(r);uint8_t*no=d+t*(D_NOPE+2*D_ROPE);uint8_t sc[8]={};quantize_nope(nv,no,sc,D_NOPE);__nv_bfloat16*ro=(__nv_bfloat16*)(no+D_NOPE);for(int i=0;i<D_ROPE;i++)ro[i]=__float2bfloat16(dist(r));memcpy(d+bs*(D_NOPE+2*D_ROPE)+t*8,sc,8);}}
struct Cfg{const char*n;int B,HQ,SQ,tm,te,mbs,ebs,skv,esk;};
int main(){
    cuInit(0);int num_sms;cudaDeviceGetAttribute(&num_sms,cudaDevAttrMultiProcessorCount,0);
    Cfg cfgs[]={{"b2_v4flash",2,64,2,128,512,256,64,16384,16384},{"b64_v4flash",64,64,2,128,512,256,64,16384,16384},{"b128_v4flash",128,64,2,128,512,256,64,16384,16384},
        {"b2_v4pro",2,128,2,128,1024,256,64,16384,16384},{"b64_v4pro",64,128,2,128,1024,256,64,16384,16384},{"b128_v4pro",128,128,2,128,1024,256,64,16384,16384}};
    int nc=6;size_t fsz=128*1024*1024;void*df;chk(cudaMalloc(&df,fsz),"f");
    printf("KERNEL_RESULT {");bool first=true;
    for(int ci=0;ci<nc;ci++){
        auto&c=cfgs[ci];int B=c.B,HQ=c.HQ,SQ=c.SQ,tm=c.tm,te=c.te,mbs=c.mbs,ebs=c.ebs;
        int mnb=(c.skv+mbs-1)/mbs,enb=(c.esk+ebs-1)/ebs;
        auto pad576=[](int bs){return((bs*BYTES_PER_TOKEN+575)/576)*576;};
        int mst=pad576(mbs),est=pad576(ebs);std::mt19937 rng(42+ci);
        size_t msz=(size_t)mnb*mst,esz=(size_t)enb*est;std::vector<uint8_t>hm(msz,0),he(esz,0);
        for(int b=0;b<mnb;b++)gen_kv(hm.data()+(size_t)b*mst,mbs,rng);
        for(int b=0;b<enb;b++)gen_kv(he.data()+(size_t)b*est,ebs,rng);
        int qt=B*SQ*HQ*D_QK;std::vector<__nv_bfloat16>hqb(qt);std::uniform_real_distribution<float>dist(-0.5f,0.5f);for(int i=0;i<qt;i++)hqb[i]=__float2bfloat16(dist(rng));
        std::vector<int>him(B*SQ*tm),hie(B*SQ*te);std::uniform_int_distribution<int>md(0,mnb*mbs-1),ed(0,enb*ebs-1);for(auto&v:him)v=md(rng);for(auto&v:hie)v=ed(rng);
        float sms=powf((float)D_QK,-0.55f),sml2=sms*1.4426950408889634f;
        __nv_bfloat16*dq;uint8_t*dm,*de;int*di,*die;__nv_bfloat16*dout;float*dlse;
        chk(cudaMalloc(&dq,qt*2),"");chk(cudaMalloc(&dm,msz),"");chk(cudaMalloc(&de,esz),"");
        chk(cudaMalloc(&di,B*SQ*tm*4),"");chk(cudaMalloc(&die,B*SQ*te*4),"");
        chk(cudaMalloc(&dout,B*SQ*HQ*D_V*2),"");chk(cudaMalloc(&dlse,B*SQ*HQ*4),"");
        chk(cudaMemcpy(dq,hqb.data(),qt*2,cudaMemcpyHostToDevice),"");chk(cudaMemcpy(dm,hm.data(),msz,cudaMemcpyHostToDevice),"");
        chk(cudaMemcpy(de,he.data(),esz,cudaMemcpyHostToDevice),"");chk(cudaMemcpy(di,him.data(),B*SQ*tm*4,cudaMemcpyHostToDevice),"");
        chk(cudaMemcpy(die,hie.data(),B*SQ*te*4,cudaMemcpyHostToDevice),"");
        // TMA tensor maps for gather4
        CUtensorMap tmap_nm,tmap_ne,tmap_rm,tmap_re;
        int tma_step_m=mst/TMA_K_STRIDE, tma_step_e=est/TMA_K_STRIDE;
        {uint64_t g[2]={(uint64_t)(D_NOPE/8),(uint64_t)mnb*(uint64_t)tma_step_m};
         uint64_t s[1]={(uint64_t)TMA_K_STRIDE};uint32_t b[2]={(uint32_t)(D_NOPE/8),1};uint32_t e[2]={1,1};
         chk(cuTensorMapEncodeTiled(&tmap_nm,CU_TENSOR_MAP_DATA_TYPE_INT64,2,(void*)dm,g,s,b,e,
            CU_TENSOR_MAP_INTERLEAVE_NONE,CU_TENSOR_MAP_SWIZZLE_NONE,CU_TENSOR_MAP_L2_PROMOTION_L2_128B,CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE),"nm");}
        {uint64_t g[2]={(uint64_t)(D_NOPE/8),(uint64_t)enb*(uint64_t)tma_step_e};
         uint64_t s[1]={(uint64_t)TMA_K_STRIDE};uint32_t b[2]={(uint32_t)(D_NOPE/8),1};uint32_t e[2]={1,1};
         chk(cuTensorMapEncodeTiled(&tmap_ne,CU_TENSOR_MAP_DATA_TYPE_INT64,2,(void*)de,g,s,b,e,
            CU_TENSOR_MAP_INTERLEAVE_NONE,CU_TENSOR_MAP_SWIZZLE_NONE,CU_TENSOR_MAP_L2_PROMOTION_L2_128B,CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE),"ne");}
        {uint64_t g[2]={(uint64_t)D_ROPE,(uint64_t)mnb*(uint64_t)tma_step_m};
         uint64_t s[1]={(uint64_t)TMA_K_STRIDE};uint32_t b[2]={(uint32_t)(D_ROPE),1};uint32_t e[2]={1,1};
         chk(cuTensorMapEncodeTiled(&tmap_rm,CU_TENSOR_MAP_DATA_TYPE_BFLOAT16,2,(void*)(dm+D_NOPE),g,s,b,e,
            CU_TENSOR_MAP_INTERLEAVE_NONE,CU_TENSOR_MAP_SWIZZLE_128B,CU_TENSOR_MAP_L2_PROMOTION_L2_128B,CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE),"rm");}
        {uint64_t g[2]={(uint64_t)D_ROPE,(uint64_t)enb*(uint64_t)tma_step_e};
         uint64_t s[1]={(uint64_t)TMA_K_STRIDE};uint32_t b[2]={(uint32_t)(D_ROPE),1};uint32_t e[2]={1,1};
         chk(cuTensorMapEncodeTiled(&tmap_re,CU_TENSOR_MAP_DATA_TYPE_BFLOAT16,2,(void*)(de+D_NOPE),g,s,b,e,
            CU_TENSOR_MAP_INTERLEAVE_NONE,CU_TENSOR_MAP_SWIZZLE_128B,CU_TENSOR_MAP_L2_PROMOTION_L2_128B,CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE),"re");}
        // TMA for Q: 4D (64, HQ, SQ, B) bf16, SW128, box=(64,B_H,1,1)
        CUtensorMap tmap_qm;
        {uint64_t g[4]={(uint64_t)D_QK,(uint64_t)HQ,(uint64_t)SQ,(uint64_t)B};
         uint64_t gs[3]={(uint64_t)(D_QK*2),(uint64_t)(HQ*D_QK*2),(uint64_t)((int64_t)SQ*HQ*D_QK*2)};
         uint32_t b2[4]={64,(uint32_t)B_H,1,1};uint32_t e2[4]={1,1,1,1};
         chk(cuTensorMapEncodeTiled(&tmap_qm,CU_TENSOR_MAP_DATA_TYPE_BFLOAT16,4,(void*)dq,g,gs,b2,e2,
            CU_TENSOR_MAP_INTERLEAVE_NONE,CU_TENSOR_MAP_SWIZZLE_128B,CU_TENSOR_MAP_L2_PROMOTION_L2_128B,CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE),"tq");}
        const uint8_t*kv_sm=dm+mbs*(D_NOPE+2*D_ROPE);
        const uint8_t*kv_se=de+ebs*(D_NOPE+2*D_ROPE);
        // TMA for O store: 4D (D_V, HQ, SQ, B) bf16, SW128, box=(64,B_H,1,1)
        CUtensorMap tmap_om;
        {uint64_t g[4]={(uint64_t)D_V,(uint64_t)HQ,(uint64_t)SQ,(uint64_t)B};
         uint64_t gs[3]={(uint64_t)(D_V*2),(uint64_t)(HQ*D_V*2),(uint64_t)((int64_t)SQ*HQ*D_V*2)};
         uint32_t b2[4]={64,(uint32_t)B_H,1,1};uint32_t e2[4]={1,1,1,1};
         chk(cuTensorMapEncodeTiled(&tmap_om,CU_TENSOR_MAP_DATA_TYPE_BFLOAT16,4,(void*)dout,g,gs,b2,e2,
            CU_TENSOR_MAP_INTERLEAVE_NONE,CU_TENSOR_MAP_SWIZZLE_128B,CU_TENSOR_MAP_L2_PROMOTION_NONE,CU_TENSOR_MAP_FLOAT_OOB_FILL_NONE),"to");}
        int nsmparts=(HQ==128)?std::max(num_sms/SQ/2,1):std::max(num_sms/SQ,1);int tspl=B+nsmparts;
        DecodingSchedMeta*d_sched;int*d_nsplits;float*d_oacc,*d_lseacc;
        chk(cudaMalloc(&d_sched,nsmparts*sizeof(DecodingSchedMeta)),"");chk(cudaMalloc(&d_nsplits,(B+1)*4),"");
        chk(cudaMalloc(&d_oacc,tspl*SQ*HQ*D_V*4),"");chk(cudaMalloc(&d_lseacc,tspl*SQ*HQ*4),"");
        // Validate
        bool valid=true;float me=0;
        {int vTM=std::min(tm,16),vTE=std::min(te,16),vH=std::min(HQ,2);__nv_bfloat16*vq,*vo;float*vl;int*vi,*vie;
         std::vector<__nv_bfloat16>vqh(SQ*vH*D_QK);for(int s=0;s<SQ;s++)for(int h=0;h<vH;h++)memcpy(&vqh[(s*vH+h)*D_QK],&hqb[(s*HQ+h)*D_QK],D_QK*2);
         std::vector<int>vih(SQ*vTM),vieh(SQ*vTE);for(int s=0;s<SQ;s++){for(int t=0;t<vTM;t++)vih[s*vTM+t]=him[s*tm+t];for(int t=0;t<vTE;t++)vieh[s*vTE+t]=hie[s*te+t];}
         chk(cudaMalloc(&vq,vqh.size()*2),"");chk(cudaMalloc(&vo,SQ*vH*D_V*2),"");chk(cudaMalloc(&vl,SQ*vH*4),"");chk(cudaMalloc(&vi,vih.size()*4),"");chk(cudaMalloc(&vie,vieh.size()*4),"");
         chk(cudaMemcpy(vq,vqh.data(),vqh.size()*2,cudaMemcpyHostToDevice),"");chk(cudaMemcpy(vi,vih.data(),vih.size()*4,cudaMemcpyHostToDevice),"");chk(cudaMemcpy(vie,vieh.data(),vieh.size()*4,cudaMemcpyHostToDevice),"");
         mla_validate<<<dim3(SQ,vH),128>>>(vq,(uint8_t*)dm,vi,(uint8_t*)de,vie,vo,vl,1,SQ,vH,vTM,vTE,mbs,ebs,mst,est,SQ*vH*D_QK,vH*D_QK,D_QK,SQ*vTM,vTM,SQ*vTE,vTE,SQ*vH*D_V,vH*D_V,D_V,SQ*vH,vH,sms);chk(cudaDeviceSynchronize(),"");
         std::vector<float>cpu_out(SQ*vH*D_V,0);
         for(int s=0;s<SQ;s++)for(int h=0;h<vH;h++){float q[D_QK];for(int d=0;d<D_QK;d++)q[d]=__bfloat162float(vqh[(s*vH+h)*D_QK+d]);float mi2=-1e30f,li2=0;float acc[D_V]={};
           for(int t=0;t<vTM+vTE;t++){int ti;const uint8_t*kb;int bs2,st2;if(t<vTM){ti=vih[s*vTM+t];kb=hm.data();bs2=mbs;st2=mst;}else{ti=vieh[s*vTE+(t-vTM)];kb=he.data();bs2=ebs;st2=est;}if(ti==-1)continue;float kv[D_QK];dequant_tok(kb+(int64_t)((unsigned)ti/bs2)*st2,(unsigned)ti%bs2,bs2,kv);float dot=0;for(int d=0;d<D_QK;d++)dot+=q[d]*kv[d];dot*=sms;float nm=fmaxf(mi2,dot),os=expf(mi2-nm),p=expf(dot-nm);li2=li2*os+p;mi2=nm;for(int d=0;d<D_V;d++)acc[d]=acc[d]*os+p*kv[d];}
           float il=(li2>0)?1.0f/li2:0;for(int d=0;d<D_V;d++)cpu_out[(s*vH+h)*D_V+d]=acc[d]*il;}
         std::vector<__nv_bfloat16>gpu_out(SQ*vH*D_V);chk(cudaMemcpy(gpu_out.data(),vo,gpu_out.size()*2,cudaMemcpyDeviceToHost),"");
         for(int i=0;i<SQ*vH*D_V;i++){float gv=__bfloat162float(gpu_out[i]),rv=cpu_out[i];float err=fabsf(gv-rv)/fmaxf(fabsf(rv),1e-6f);if(err>me)me=err;}
         valid=(me<1e-2f);fprintf(stderr,"%s: val err=%.6f %s\n",c.n,me,valid?"PASS":"FAIL");cudaFree(vq);cudaFree(vo);cudaFree(vl);cudaFree(vi);cudaFree(vie);}
        double tflops=0;
        if(valid){
            {GetDecodeSchedMetaParams sp;sp.b=B;sp.s_q=SQ;sp.block_size_n=B_TOPK;sp.fixed_overhead_num_blocks=(HQ<=64)?5:1;sp.topk=tm;sp.extra_topk=te;sp.seqlens_k_ptr=nullptr;sp.topk_length=nullptr;sp.extra_topk_length=nullptr;sp.tile_scheduler_metadata_ptr=d_sched;sp.num_splits_ptr=d_nsplits;sp.num_sm_parts=nsmparts;sp.stream=0;int smem=sizeof(int)*(B*5+1);cudaFuncSetAttribute(my_sched_kernel,cudaFuncAttributeMaxDynamicSharedMemorySize,smem);my_sched_kernel<<<1,32,smem>>>(sp);}cudaDeviceSynchronize();
            auto run_kernel=[&](){
                int attn_smem=sizeof(SmemPlan);
                cudaFuncSetAttribute(my_attn_kernel_v3,cudaFuncAttributeMaxDynamicSharedMemorySize,attn_smem);
                int nhg=(HQ+B_H-1)/B_H;my_attn_kernel_v3<<<dim3(SQ,nsmparts,nhg),NUM_THREADS,attn_smem>>>(
                    tmap_nm,tmap_ne,tmap_rm,tmap_re,tmap_qm,
                    dq,di,die,d_oacc,d_lseacc,dout,dlse,d_sched,d_nsplits,
                    B,SQ,HQ,tm,te,mbs,ebs,(int64_t)mst,(int64_t)est,
                    SQ*HQ*D_QK,HQ*D_QK,D_QK,SQ*tm,tm,SQ*te,te,
                    SQ*HQ*D_V,HQ*D_V,D_V,SQ*HQ,HQ,
                    SQ*HQ*D_V,HQ*D_V,D_V,SQ*HQ,HQ,sml2,
                    tma_step_m,tma_step_e,kv_sm,kv_se,tmap_om);
                constexpr int BM=8;int gz=(HQ+BM-1)/BM;CombineParams cp;cp.b=B;cp.s_q=SQ;cp.h_q=HQ;cp.d_v=D_V;cp.lse=dlse;cp.out=dout;cp.stride_lse_b=SQ*HQ;cp.stride_lse_s_q=HQ;cp.stride_o_b=SQ*HQ*D_V;cp.stride_o_s_q=HQ*D_V;cp.stride_o_h_q=D_V;cp.lse_accum=d_lseacc;cp.o_accum=d_oacc;cp.stride_lse_accum_split=SQ*HQ;cp.stride_lse_accum_s_q=HQ;cp.stride_o_accum_split=SQ*HQ*D_V;cp.stride_o_accum_s_q=HQ*D_V;cp.stride_o_accum_h_q=D_V;cp.tile_scheduler_metadata_ptr=d_sched;cp.num_splits_ptr=d_nsplits;cp.num_sm_parts=nsmparts;cp.attn_sink=nullptr;cp.stream=0;
                if(nsmparts<=32)my_combine_kernel<D_V,BM,32><<<dim3(B,SQ,gz),BM*32>>>(cp);else if(nsmparts<=64)my_combine_kernel<D_V,BM,64><<<dim3(B,SQ,gz),BM*32>>>(cp);else if(nsmparts<=96)my_combine_kernel<D_V,BM,96><<<dim3(B,SQ,gz),BM*32>>>(cp);else my_combine_kernel<D_V,BM,128><<<dim3(B,SQ,gz),BM*32>>>(cp);};
            for(int i=0;i<20;i++){run_kernel();cudaDeviceSynchronize();}
            int NI=100;std::vector<float>ts(NI);for(int it=0;it<NI;it++){chk(cudaMemset(df,0,fsz),"");cudaEvent_t t0,t1;cudaEventCreate(&t0);cudaEventCreate(&t1);cudaEventRecord(t0);run_kernel();cudaEventRecord(t1);cudaEventSynchronize(t1);float ms;cudaEventElapsedTime(&ms,t0,t1);ts[it]=ms;cudaEventDestroy(t0);cudaEventDestroy(t1);}
            std::sort(ts.begin(),ts.end());float med=ts[NI/2];double flop=2.0*HQ*((double)B*SQ*(tm+te))*(D_QK+D_V);tflops=flop/(med/1000.0)/1e12;fprintf(stderr,"%s: %.2f TFLOPS, %.1f us\n",c.n,tflops,med*1000);}
        if(!first)printf(", ");first=false;if(valid)printf("\"%s\": %.4f",c.n,tflops);else{printf("\"%s\": 0.0",c.n);fprintf(stderr,"INVALID: %s\n",c.n);}
        cudaFree(dq);cudaFree(dm);cudaFree(de);cudaFree(di);cudaFree(die);cudaFree(dout);cudaFree(dlse);cudaFree(d_sched);cudaFree(d_nsplits);cudaFree(d_oacc);cudaFree(d_lseacc);}
    printf("}\n");fflush(stdout);fflush(stderr);usleep(500000);fprintf(stderr,"Running baseline...\n");
    FILE*bp=popen("python3 ../baselines/fp8-mla-decode-dsv4/baseline_dsv4_decode.py 2>/dev/null","r");double ref[6]={};const char*rn[6]={"b2_v4flash","b64_v4flash","b128_v4flash","b2_v4pro","b64_v4pro","b128_v4pro"};
    if(bp){char l[1024];while(fgets(l,sizeof(l),bp))for(int i=0;i<6;i++)if(strstr(l,rn[i])&&strstr(l,"TFLOPS")){char*p=strstr(l,":");if(p)ref[i]=atof(p+1);}pclose(bp);}
    printf("KERNEL_RESULT_REFERENCE {");for(int i=0;i<6;i++){if(i)printf(", ");printf("\"%s\": %.2f",rn[i],ref[i]);}printf("}\n");cudaFree(df);return 0;}
